using TwoButton.Core.Model;

namespace TwoButton.Core.Jobs.Ninja;

/// <summary>
/// Ninja action and status ids.
/// <para>
/// Generated by <c>tools/generate_action_tables.py</c> from BossMod's ActionQueue
/// definitions (BSD 3-Clause), which are regenerated from the game's own data each
/// patch. Do not edit by hand - rerun the generator instead.
/// </para>
/// <para>
/// Ids are still verified against the game's Action and Status sheets at startup and
/// repaired by name on a mismatch, so a patch that shuffles them is corrected rather
/// than mis-cast.
/// </para>
/// </summary>
public static class NinjaActions
{
    public static readonly ActionRef SpinningEdge = new(2240, "Spinning Edge", ActionKind.Gcd, 1);
    public static readonly ActionRef ShadeShift = new(2241, "Shade Shift", ActionKind.OGcd, 2);
    public static readonly ActionRef GustSlash = new(2242, "Gust Slash", ActionKind.Gcd, 4);
    public static readonly ActionRef Hide = new(2245, "Hide", ActionKind.OGcd, 10);
    public static readonly ActionRef ThrowingDagger = new(2247, "Throwing Dagger", ActionKind.Gcd, 15);
    public static readonly ActionRef Mug = new(2248, "Mug", ActionKind.OGcd, 15);
    public static readonly ActionRef TrickAttack = new(2258, "Trick Attack", ActionKind.OGcd, 18);
    public static readonly ActionRef AeolianEdge = new(2255, "Aeolian Edge", ActionKind.Gcd, 26);
    public static readonly ActionRef FumaShuriken = new(2265, "Fuma Shuriken", ActionKind.Gcd, 30);
    public static readonly ActionRef Ninjutsu = new(2260, "Ninjutsu", ActionKind.Gcd, 30);
    public static readonly ActionRef FumaJin = new(18875, "Fuma Jin", ActionKind.Gcd, 30);
    public static readonly ActionRef FumaChi = new(18874, "Fuma Chi", ActionKind.Gcd, 30);
    public static readonly ActionRef FumaTen = new(18873, "Fuma Ten", ActionKind.Gcd, 30);
    public static readonly ActionRef Ten1 = new(2259, "Ten", ActionKind.Gcd, 30);
    public static readonly ActionRef RabbitMedium = new(2272, "Rabbit Medium", ActionKind.Gcd, 30);
    public static readonly ActionRef Ten2 = new(18805, "Ten II", ActionKind.Gcd, 30);
    public static readonly ActionRef TCJRaiton = new(18877, "T C J Raiton", ActionKind.Gcd, 35);
    public static readonly ActionRef Chi2 = new(18806, "Chi II", ActionKind.Gcd, 35);
    public static readonly ActionRef Raiton = new(2267, "Raiton", ActionKind.Gcd, 35);
    public static readonly ActionRef TCJKaton = new(18876, "T C J Katon", ActionKind.Gcd, 35);
    public static readonly ActionRef Chi1 = new(2261, "Chi", ActionKind.Gcd, 35);
    public static readonly ActionRef Katon = new(2266, "Katon", ActionKind.Gcd, 35);
    public static readonly ActionRef DeathBlossom = new(2254, "Death Blossom", ActionKind.Gcd, 38);
    public static readonly ActionRef Assassinate = new(2246, "Assassinate", ActionKind.OGcd, 40);
    public static readonly ActionRef Shukuchi = new(2262, "Shukuchi", ActionKind.OGcd, 40);
    public static readonly ActionRef Jin1 = new(2263, "Jin", ActionKind.Gcd, 45);
    public static readonly ActionRef TCJSuiton = new(18881, "T C J Suiton", ActionKind.Gcd, 45);
    public static readonly ActionRef TCJDoton = new(18880, "T C J Doton", ActionKind.Gcd, 45);
    public static readonly ActionRef TCJHuton = new(18879, "T C J Huton", ActionKind.Gcd, 45);
    public static readonly ActionRef TCJHyoton = new(18878, "T C J Hyoton", ActionKind.Gcd, 45);
    public static readonly ActionRef Hyoton = new(2268, "Hyoton", ActionKind.Gcd, 45);
    public static readonly ActionRef Huton = new(2269, "Huton", ActionKind.Gcd, 45);
    public static readonly ActionRef Suiton = new(2271, "Suiton", ActionKind.Gcd, 45);
    public static readonly ActionRef Jin2 = new(18807, "Jin II", ActionKind.Gcd, 45);
    public static readonly ActionRef Doton = new(2270, "Doton", ActionKind.Gcd, 45);
    public static readonly ActionRef Kassatsu = new(2264, "Kassatsu", ActionKind.OGcd, 50);
    public static readonly ActionRef HakkeMujinsatsu = new(16488, "Hakke Mujinsatsu", ActionKind.Gcd, 52);
    public static readonly ActionRef ArmorCrush = new(3563, "Armor Crush", ActionKind.Gcd, 54);
    public static readonly ActionRef DreamWithinADream = new(3566, "Dream Within A Dream", ActionKind.OGcd, 56);
    public static readonly ActionRef HellfrogMedium = new(7401, "Hellfrog Medium", ActionKind.OGcd, 62);
    public static readonly ActionRef Dokumori = new(36957, "Dokumori", ActionKind.OGcd, 66);
    public static readonly ActionRef Bhavacakra = new(7402, "Bhavacakra", ActionKind.OGcd, 68);
    public static readonly ActionRef TenChiJin = new(7403, "Ten Chi Jin", ActionKind.OGcd, 70);
    public static readonly ActionRef Meisui = new(16489, "Meisui", ActionKind.OGcd, 72);
    public static readonly ActionRef HyoshoRanryu = new(16492, "Hyosho Ranryu", ActionKind.Gcd, 76);
    public static readonly ActionRef GokaMekkyaku = new(16491, "Goka Mekkyaku", ActionKind.Gcd, 76);
    public static readonly ActionRef Bunshin = new(16493, "Bunshin", ActionKind.OGcd, 80);
    public static readonly ActionRef PhantomKamaitachi = new(25774, "Phantom Kamaitachi", ActionKind.Gcd, 82);
    public static readonly ActionRef HollowNozuchi = new(25776, "Hollow Nozuchi", ActionKind.OGcd, 86);
    public static readonly ActionRef FleetingRaiju = new(25778, "Fleeting Raiju", ActionKind.Gcd, 90);
    public static readonly ActionRef ForkedRaiju = new(25777, "Forked Raiju", ActionKind.Gcd, 90);
    public static readonly ActionRef KunaisBane = new(36958, "Kunais Bane", ActionKind.OGcd, 92);
    public static readonly ActionRef DeathfrogMedium = new(36959, "Deathfrog Medium", ActionKind.OGcd, 96);
    public static readonly ActionRef ZeshoMeppo = new(36960, "Zesho Meppo", ActionKind.OGcd, 96);
    public static readonly ActionRef TenriJindo = new(36961, "Tenri Jindo", ActionKind.OGcd, 100);
    public static readonly ActionRef SecondWind = new(7541, "Second Wind", ActionKind.OGcd, 8);
    public static readonly ActionRef LegSweep = new(7863, "Leg Sweep", ActionKind.OGcd, 10);
    public static readonly ActionRef Bloodbath = new(7542, "Bloodbath", ActionKind.OGcd, 12);
    public static readonly ActionRef Feint = new(7549, "Feint", ActionKind.OGcd, 22);
    public static readonly ActionRef ArmsLength = new(7548, "Arms Length", ActionKind.OGcd, 32);
    public static readonly ActionRef TrueNorth = new(7546, "True North", ActionKind.OGcd, 50);

    public static readonly StatusRef ShadeShiftBuff = new(488, "Shade Shift");
    public static readonly StatusRef Hidden = new(614, "Hidden");
    public static readonly StatusRef BloodbathBuff = new(84, "Bloodbath");
    public static readonly StatusRef TrickAttackBuff = new(3254, "Trick Attack");
    public static readonly StatusRef KunaisBaneBuff = new(3906, "Kunais Bane");
    public static readonly StatusRef TenChiJinBuff = new(1186, "Ten Chi Jin");
    public static readonly StatusRef Mudra = new(496, "Mudra");
    public static readonly StatusRef RaijuReady = new(2690, "Raiju Ready");
    public static readonly StatusRef ShadowWalker = new(3848, "Shadow Walker");
    public static readonly StatusRef KassatsuBuff = new(497, "Kassatsu");
    public static readonly StatusRef Higi = new(3850, "Higi");
    public static readonly StatusRef VulnerabilityUp = new(638, "Vulnerability Up");
    public static readonly StatusRef DokumoriBuff = new(3849, "Dokumori");
    public static readonly StatusRef TenriJindoReady = new(3851, "Tenri Jindo Ready");
    public static readonly StatusRef MeisuiBuff = new(2689, "Meisui");
    public static readonly StatusRef BunshinBuff = new(1954, "Bunshin");
    public static readonly StatusRef PhantomKamaitachiReady = new(2723, "Phantom Kamaitachi Ready");
    public static readonly StatusRef FeintBuff = new(1195, "Feint");
    public static readonly StatusRef TrueNorthBuff = new(1250, "True North");

    public static readonly IReadOnlyList<ActionRef> All =
    [
        SpinningEdge, ShadeShift, GustSlash, Hide,
        ThrowingDagger, Mug, TrickAttack, AeolianEdge,
        FumaShuriken, Ninjutsu, FumaJin, FumaChi,
        FumaTen, Ten1, RabbitMedium, Ten2,
        TCJRaiton, Chi2, Raiton, TCJKaton,
        Chi1, Katon, DeathBlossom, Assassinate,
        Shukuchi, Jin1, TCJSuiton, TCJDoton,
        TCJHuton, TCJHyoton, Hyoton, Huton,
        Suiton, Jin2, Doton, Kassatsu,
        HakkeMujinsatsu, ArmorCrush, DreamWithinADream, HellfrogMedium,
        Dokumori, Bhavacakra, TenChiJin, Meisui,
        HyoshoRanryu, GokaMekkyaku, Bunshin, PhantomKamaitachi,
        HollowNozuchi, FleetingRaiju, ForkedRaiju, KunaisBane,
        DeathfrogMedium, ZeshoMeppo, TenriJindo, SecondWind,
        LegSweep, Bloodbath, Feint, ArmsLength,
        TrueNorth,
    ];

    public static readonly IReadOnlyList<StatusRef> AllStatuses =
    [
        ShadeShiftBuff, Hidden, BloodbathBuff, TrickAttackBuff,
        KunaisBaneBuff, TenChiJinBuff, Mudra, RaijuReady,
        ShadowWalker, KassatsuBuff, Higi, VulnerabilityUp,
        DokumoriBuff, TenriJindoReady, MeisuiBuff, BunshinBuff,
        PhantomKamaitachiReady, FeintBuff, TrueNorthBuff,
    ];
}
