using OneTwoPunch.Core.Model;

namespace OneTwoPunch.Core.Jobs.Warrior;

/// <summary>
/// Warrior action and status ids.
/// <para>
/// Generated by <c>tools/generate_action_tables.py</c> from BossMod's ActionQueue
/// definitions (BSD 3-Clause), which are regenerated from the game's own data each
/// patch. Do not edit by hand - rerun the generator instead.
/// </para>
/// <para>
/// Ids are still verified against the game's Action and Status sheets at startup and
/// repaired by name on a mismatch, so a patch that shuffles them is corrected rather
/// than mis-cast.
/// </para>
/// </summary>
public static class WarriorActions
{
    public static readonly ActionRef HeavySwing = new(31, "Heavy Swing", ActionKind.Gcd, 1);
    public static readonly ActionRef Maim = new(37, "Maim", ActionKind.Gcd, 4);
    public static readonly ActionRef Berserk = new(38, "Berserk", ActionKind.OGcd, 6);
    public static readonly ActionRef Overpower = new(41, "Overpower", ActionKind.Gcd, 10);
    public static readonly ActionRef Defiance = new(48, "Defiance", ActionKind.OGcd, 10);
    public static readonly ActionRef ReleaseDefiance = new(32066, "Release Defiance", ActionKind.OGcd, 10);
    public static readonly ActionRef Tomahawk = new(46, "Tomahawk", ActionKind.Gcd, 15);
    public static readonly ActionRef StormPath = new(42, "Storm Path", ActionKind.Gcd, 26);
    public static readonly ActionRef ThrillOfBattle = new(40, "Thrill of Battle", ActionKind.OGcd, 30);
    public static readonly ActionRef InnerBeast = new(49, "Inner Beast", ActionKind.Gcd, 35);
    public static readonly ActionRef Vengeance = new(44, "Vengeance", ActionKind.OGcd, 38);
    public static readonly ActionRef MythrilTempest = new(16462, "Mythril Tempest", ActionKind.Gcd, 40);
    public static readonly ActionRef Holmgang = new(43, "Holmgang", ActionKind.OGcd, 42);
    public static readonly ActionRef SteelCyclone = new(51, "Steel Cyclone", ActionKind.Gcd, 45);
    public static readonly ActionRef StormEye = new(45, "Storm Eye", ActionKind.Gcd, 50);
    public static readonly ActionRef Infuriate = new(52, "Infuriate", ActionKind.OGcd, 50);
    public static readonly ActionRef FellCleave = new(3549, "Fell Cleave", ActionKind.Gcd, 54);
    public static readonly ActionRef RawIntuition = new(3551, "Raw Intuition", ActionKind.OGcd, 56);
    public static readonly ActionRef Equilibrium = new(3552, "Equilibrium", ActionKind.OGcd, 58);
    public static readonly ActionRef Decimate = new(3550, "Decimate", ActionKind.Gcd, 60);
    public static readonly ActionRef Onslaught = new(7386, "Onslaught", ActionKind.OGcd, 62);
    public static readonly ActionRef Upheaval = new(7387, "Upheaval", ActionKind.OGcd, 64);
    public static readonly ActionRef ShakeItOff = new(7388, "Shake It Off", ActionKind.OGcd, 68);
    public static readonly ActionRef InnerRelease = new(7389, "Inner Release", ActionKind.OGcd, 70);
    public static readonly ActionRef ChaoticCyclone = new(16463, "Chaotic Cyclone", ActionKind.Gcd, 72);
    public static readonly ActionRef NascentFlash = new(16464, "Nascent Flash", ActionKind.OGcd, 76);
    public static readonly ActionRef InnerChaos = new(16465, "Inner Chaos", ActionKind.Gcd, 80);
    public static readonly ActionRef Bloodwhetting = new(25751, "Bloodwhetting", ActionKind.OGcd, 82);
    public static readonly ActionRef Orogeny = new(25752, "Orogeny", ActionKind.OGcd, 86);
    public static readonly ActionRef PrimalRend = new(25753, "Primal Rend", ActionKind.Gcd, 90);
    public static readonly ActionRef Damnation = new(36923, "Damnation", ActionKind.OGcd, 92);
    public static readonly ActionRef PrimalWrath = new(36924, "Primal Wrath", ActionKind.OGcd, 96);
    public static readonly ActionRef PrimalRuination = new(36925, "Primal Ruination", ActionKind.Gcd, 100);
    public static readonly ActionRef Rampart = new(7531, "Rampart", ActionKind.OGcd, 8);
    public static readonly ActionRef LowBlow = new(7540, "Low Blow", ActionKind.OGcd, 12);
    public static readonly ActionRef Provoke = new(7533, "Provoke", ActionKind.OGcd, 15);
    public static readonly ActionRef Interject = new(7538, "Interject", ActionKind.OGcd, 18);
    public static readonly ActionRef Reprisal = new(7535, "Reprisal", ActionKind.OGcd, 22);
    public static readonly ActionRef ArmsLength = new(7548, "Arms Length", ActionKind.OGcd, 32);
    public static readonly ActionRef Shirk = new(7537, "Shirk", ActionKind.OGcd, 48);

    public static readonly StatusRef SurgingTempest = new(2677, "Surging Tempest");
    public static readonly StatusRef NascentChaos = new(1897, "Nascent Chaos");
    public static readonly StatusRef BerserkBuff = new(86, "Berserk");
    public static readonly StatusRef InnerReleaseBuff = new(1177, "Inner Release");
    public static readonly StatusRef PrimalRendBuff = new(2624, "Primal Rend");
    public static readonly StatusRef InnerStrength = new(2663, "Inner Strength");
    public static readonly StatusRef BurgeoningFury = new(3833, "Burgeoning Fury");
    public static readonly StatusRef Wrathful = new(3901, "Wrathful");
    public static readonly StatusRef PrimalRuinationReady = new(3834, "Primal Ruination Ready");
    public static readonly StatusRef VengeanceRetaliation = new(89, "Vengeance Retaliation");
    public static readonly StatusRef VengeanceDefense = new(912, "Vengeance Defense");
    public static readonly StatusRef DamnationBuff = new(3832, "Damnation");
    public static readonly StatusRef PrimevalImpulse = new(3900, "Primeval Impulse");
    public static readonly StatusRef RampartBuff = new(1191, "Rampart");
    public static readonly StatusRef ThrillOfBattleBuff = new(87, "Thrill of Battle");
    public static readonly StatusRef HolmgangBuff = new(409, "Holmgang");
    public static readonly StatusRef EquilibriumRegen = new(2681, "Equilibrium Regen");
    public static readonly StatusRef ShakeItOffBuff = new(1457, "Shake It Off");
    public static readonly StatusRef ShakeItOffHOT = new(2108, "Shake It Off HOT");
    public static readonly StatusRef RawIntuitionBuff = new(735, "Raw Intuition");
    public static readonly StatusRef NascentFlashSelf = new(1857, "Nascent Flash Self");
    public static readonly StatusRef NascentFlashTarget = new(1858, "Nascent Flash Target");
    public static readonly StatusRef BloodwhettingDefenseLong = new(2678, "Bloodwhetting Defense Long");
    public static readonly StatusRef BloodwhettingDefenseShort = new(2679, "Bloodwhetting Defense Short");
    public static readonly StatusRef BloodwhettingShield = new(2680, "Bloodwhetting Shield");
    public static readonly StatusRef ArmsLengthBuff = new(1209, "Arms Length");
    public static readonly StatusRef DefianceBuff = new(91, "Defiance");
    public static readonly StatusRef Stun = new(2, "Stun");
    public static readonly StatusRef ShieldWall = new(194, "Shield Wall");
    public static readonly StatusRef Stronghold = new(195, "Stronghold");
    public static readonly StatusRef LandWaker = new(863, "Land Waker");
    public static readonly StatusRef BannerOfHonoredSacrifice = new(2327, "Banner of Honored Sacrifice");
    public static readonly StatusRef LostFontOfPower = new(2346, "Lost Font of Power");
    public static readonly StatusRef LostBloodRage = new(2566, "Lost Blood Rage");
    public static readonly StatusRef BloodRush = new(2567, "Blood Rush");
    public static readonly StatusRef ReprisalBuff = new(1193, "Reprisal");

    public static readonly IReadOnlyList<ActionRef> All =
    [
        HeavySwing, Maim, Berserk, Overpower,
        Defiance, ReleaseDefiance, Tomahawk, StormPath,
        ThrillOfBattle, InnerBeast, Vengeance, MythrilTempest,
        Holmgang, SteelCyclone, StormEye, Infuriate,
        FellCleave, RawIntuition, Equilibrium, Decimate,
        Onslaught, Upheaval, ShakeItOff, InnerRelease,
        ChaoticCyclone, NascentFlash, InnerChaos, Bloodwhetting,
        Orogeny, PrimalRend, Damnation, PrimalWrath,
        PrimalRuination, Rampart, LowBlow, Provoke,
        Interject, Reprisal, ArmsLength, Shirk,
    ];

    public static readonly IReadOnlyList<StatusRef> AllStatuses =
    [
        SurgingTempest, NascentChaos, BerserkBuff, InnerReleaseBuff,
        PrimalRendBuff, InnerStrength, BurgeoningFury, Wrathful,
        PrimalRuinationReady, VengeanceRetaliation, VengeanceDefense, DamnationBuff,
        PrimevalImpulse, RampartBuff, ThrillOfBattleBuff, HolmgangBuff,
        EquilibriumRegen, ShakeItOffBuff, ShakeItOffHOT, RawIntuitionBuff,
        NascentFlashSelf, NascentFlashTarget, BloodwhettingDefenseLong, BloodwhettingDefenseShort,
        BloodwhettingShield, ArmsLengthBuff, DefianceBuff, Stun,
        ShieldWall, Stronghold, LandWaker, BannerOfHonoredSacrifice,
        LostFontOfPower, LostBloodRage, BloodRush, ReprisalBuff,
    ];
}
