using OneTwoPunch.Core.Model;

namespace OneTwoPunch.Core.Jobs.Gunbreaker;

/// <summary>
/// Gunbreaker action and status ids.
/// <para>
/// Generated by <c>tools/generate_action_tables.py</c> from BossMod's ActionQueue
/// definitions (BSD 3-Clause), which are regenerated from the game's own data each
/// patch. Do not edit by hand - rerun the generator instead.
/// </para>
/// <para>
/// Ids are still verified against the game's Action and Status sheets at startup and
/// repaired by name on a mismatch, so a patch that shuffles them is corrected rather
/// than mis-cast.
/// </para>
/// </summary>
public static class GunbreakerActions
{
    public static readonly ActionRef KeenEdge = new(16137, "Keen Edge", ActionKind.Gcd, 1);
    public static readonly ActionRef NoMercy = new(16138, "No Mercy", ActionKind.OGcd, 2);
    public static readonly ActionRef BrutalShell = new(16139, "Brutal Shell", ActionKind.Gcd, 4);
    public static readonly ActionRef Camouflage = new(16140, "Camouflage", ActionKind.OGcd, 6);
    public static readonly ActionRef DemonSlice = new(16141, "Demon Slice", ActionKind.Gcd, 10);
    public static readonly ActionRef RoyalGuard = new(16142, "Royal Guard", ActionKind.OGcd, 10);
    public static readonly ActionRef ReleaseRoyalGuard = new(32068, "Release Royal Guard", ActionKind.OGcd, 10);
    public static readonly ActionRef LightningShot = new(16143, "Lightning Shot", ActionKind.Gcd, 15);
    public static readonly ActionRef DangerZone = new(16144, "Danger Zone", ActionKind.OGcd, 18);
    public static readonly ActionRef SolidBarrel = new(16145, "Solid Barrel", ActionKind.Gcd, 26);
    public static readonly ActionRef BurstStrike = new(16162, "Burst Strike", ActionKind.Gcd, 30);
    public static readonly ActionRef Nebula = new(16148, "Nebula", ActionKind.OGcd, 38);
    public static readonly ActionRef DemonSlaughter = new(16149, "Demon Slaughter", ActionKind.Gcd, 40);
    public static readonly ActionRef Aurora = new(16151, "Aurora", ActionKind.OGcd, 45);
    public static readonly ActionRef Superbolide = new(16152, "Superbolide", ActionKind.OGcd, 50);
    public static readonly ActionRef SonicBreak = new(16153, "Sonic Break", ActionKind.Gcd, 54);
    public static readonly ActionRef Trajectory = new(36934, "Trajectory", ActionKind.OGcd, 56);
    public static readonly ActionRef GnashingFang = new(16146, "Gnashing Fang", ActionKind.Gcd, 60);
    public static readonly ActionRef SavageClaw = new(16147, "Savage Claw", ActionKind.Gcd, 60);
    public static readonly ActionRef WickedTalon = new(16150, "Wicked Talon", ActionKind.Gcd, 60);
    public static readonly ActionRef BowShock = new(16159, "Bow Shock", ActionKind.OGcd, 62);
    public static readonly ActionRef HeartOfLight = new(16160, "Heart of Light", ActionKind.OGcd, 64);
    public static readonly ActionRef HeartOfStone = new(16161, "Heart of Stone", ActionKind.OGcd, 68);
    public static readonly ActionRef AbdomenTear = new(16157, "Abdomen Tear", ActionKind.OGcd, 70);
    public static readonly ActionRef JugularRip = new(16156, "Jugular Rip", ActionKind.OGcd, 70);
    public static readonly ActionRef EyeGouge = new(16158, "Eye Gouge", ActionKind.OGcd, 70);
    public static readonly ActionRef Continuation = new(16155, "Continuation", ActionKind.OGcd, 70);
    public static readonly ActionRef FatedCircle = new(16163, "Fated Circle", ActionKind.Gcd, 72);
    public static readonly ActionRef Bloodfest = new(16164, "Bloodfest", ActionKind.OGcd, 76);
    public static readonly ActionRef BlastingZone = new(16165, "Blasting Zone", ActionKind.OGcd, 80);
    public static readonly ActionRef HeartOfCorundum = new(25758, "Heart of Corundum", ActionKind.OGcd, 82);
    public static readonly ActionRef Hypervelocity = new(25759, "Hypervelocity", ActionKind.OGcd, 86);
    public static readonly ActionRef DoubleDown = new(25760, "Double Down", ActionKind.Gcd, 90);
    public static readonly ActionRef GreatNebula = new(36935, "Great Nebula", ActionKind.OGcd, 92);
    public static readonly ActionRef FatedBrand = new(36936, "Fated Brand", ActionKind.OGcd, 96);
    public static readonly ActionRef ReignOfBeasts = new(36937, "Reign of Beasts", ActionKind.Gcd, 100);
    public static readonly ActionRef NobleBlood = new(36938, "Noble Blood", ActionKind.Gcd, 100);
    public static readonly ActionRef LionHeart = new(36939, "Lion Heart", ActionKind.Gcd, 100);
    public static readonly ActionRef Rampart = new(7531, "Rampart", ActionKind.OGcd, 8);
    public static readonly ActionRef LowBlow = new(7540, "Low Blow", ActionKind.OGcd, 12);
    public static readonly ActionRef Provoke = new(7533, "Provoke", ActionKind.OGcd, 15);
    public static readonly ActionRef Interject = new(7538, "Interject", ActionKind.OGcd, 18);
    public static readonly ActionRef Reprisal = new(7535, "Reprisal", ActionKind.OGcd, 22);
    public static readonly ActionRef ArmsLength = new(7548, "Arms Length", ActionKind.OGcd, 32);
    public static readonly ActionRef Shirk = new(7537, "Shirk", ActionKind.OGcd, 48);

    public static readonly StatusRef BrutalShellBuff = new(1898, "Brutal Shell");
    public static readonly StatusRef NoMercyBuff = new(1831, "No Mercy");
    public static readonly StatusRef ReadyToRip = new(1842, "Ready to Rip");
    public static readonly StatusRef SonicBreakBuff = new(1837, "Sonic Break");
    public static readonly StatusRef BowShockBuff = new(1838, "Bow Shock");
    public static readonly StatusRef ReadyToTear = new(1843, "Ready to Tear");
    public static readonly StatusRef ReadyToGouge = new(1844, "Ready to Gouge");
    public static readonly StatusRef ReadyToBlast = new(2686, "Ready to Blast");
    public static readonly StatusRef NebulaBuff = new(1834, "Nebula");
    public static readonly StatusRef RampartBuff = new(1191, "Rampart");
    public static readonly StatusRef CamouflageBuff = new(1832, "Camouflage");
    public static readonly StatusRef ArmsLengthBuff = new(1209, "Arms Length");
    public static readonly StatusRef HeartOfLightBuff = new(1839, "Heart of Light");
    public static readonly StatusRef AuroraBuff = new(1835, "Aurora");
    public static readonly StatusRef SuperbolideBuff = new(1836, "Superbolide");
    public static readonly StatusRef HeartOfCorundumBuff = new(2683, "Heart of Corundum");
    public static readonly StatusRef ClarityOfCorundum = new(2684, "Clarity of Corundum");
    public static readonly StatusRef CatharsisOfCorundum = new(2685, "Catharsis of Corundum");
    public static readonly StatusRef RoyalGuardBuff = new(1833, "Royal Guard");
    public static readonly StatusRef Stun = new(2, "Stun");
    public static readonly StatusRef GreatNebulaBuff = new(3838, "Great Nebula");
    public static readonly StatusRef ReadyToRaze = new(3839, "Ready to Raze");
    public static readonly StatusRef ReadyToBreak = new(3886, "Ready to Break");
    public static readonly StatusRef ReadyToReign = new(3840, "Ready to Reign");
    public static readonly StatusRef BloodfestBuff = new(5051, "Bloodfest");
    public static readonly StatusRef ReprisalBuff = new(1193, "Reprisal");

    public static readonly IReadOnlyList<ActionRef> All =
    [
        KeenEdge, NoMercy, BrutalShell, Camouflage,
        DemonSlice, RoyalGuard, ReleaseRoyalGuard, LightningShot,
        DangerZone, SolidBarrel, BurstStrike, Nebula,
        DemonSlaughter, Aurora, Superbolide, SonicBreak,
        Trajectory, GnashingFang, SavageClaw, WickedTalon,
        BowShock, HeartOfLight, HeartOfStone, AbdomenTear,
        JugularRip, EyeGouge, Continuation, FatedCircle,
        Bloodfest, BlastingZone, HeartOfCorundum, Hypervelocity,
        DoubleDown, GreatNebula, FatedBrand, ReignOfBeasts,
        NobleBlood, LionHeart, Rampart, LowBlow,
        Provoke, Interject, Reprisal, ArmsLength,
        Shirk,
    ];

    public static readonly IReadOnlyList<StatusRef> AllStatuses =
    [
        BrutalShellBuff, NoMercyBuff, ReadyToRip, SonicBreakBuff,
        BowShockBuff, ReadyToTear, ReadyToGouge, ReadyToBlast,
        NebulaBuff, RampartBuff, CamouflageBuff, ArmsLengthBuff,
        HeartOfLightBuff, AuroraBuff, SuperbolideBuff, HeartOfCorundumBuff,
        ClarityOfCorundum, CatharsisOfCorundum, RoyalGuardBuff, Stun,
        GreatNebulaBuff, ReadyToRaze, ReadyToBreak, ReadyToReign,
        BloodfestBuff, ReprisalBuff,
    ];
}
