using TwoButton.Core.Model;

namespace TwoButton.Core.Jobs.Pictomancer;

/// <summary>
/// Pictomancer action and status ids.
/// <para>
/// Generated by <c>tools/generate_action_tables.py</c> from BossMod's ActionQueue
/// definitions (BSD 3-Clause), which are regenerated from the game's own data each
/// patch. Do not edit by hand - rerun the generator instead.
/// </para>
/// <para>
/// Ids are still verified against the game's Action and Status sheets at startup and
/// repaired by name on a mismatch, so a patch that shuffles them is corrected rather
/// than mis-cast.
/// </para>
/// </summary>
public static class PictomancerActions
{
    public static readonly ActionRef FireInRed = new(34650, "Fire in Red", ActionKind.Gcd, 1);
    public static readonly ActionRef AeroInGreen = new(34651, "Aero in Green", ActionKind.Gcd, 5);
    public static readonly ActionRef TemperaCoat = new(34685, "Tempera Coat", ActionKind.OGcd, 10);
    public static readonly ActionRef WaterInBlue = new(34652, "Water in Blue", ActionKind.Gcd, 15);
    public static readonly ActionRef Smudge = new(34684, "Smudge", ActionKind.OGcd, 20);
    public static readonly ActionRef FireIIInRed = new(34656, "Fire II in Red", ActionKind.Gcd, 25);
    public static readonly ActionRef WingedMuse = new(34671, "Winged Muse", ActionKind.OGcd, 30);
    public static readonly ActionRef LivingMuse = new(35347, "Living Muse", ActionKind.OGcd, 30);
    public static readonly ActionRef CreatureMotif = new(34689, "Creature Motif", ActionKind.Gcd, 30);
    public static readonly ActionRef WingMotif = new(34665, "Wing Motif", ActionKind.Gcd, 30);
    public static readonly ActionRef MogOfTheAges = new(34676, "Mog of the Ages", ActionKind.OGcd, 30);
    public static readonly ActionRef PomMotif = new(34664, "Pom Motif", ActionKind.Gcd, 30);
    public static readonly ActionRef PomMuse = new(34670, "Pom Muse", ActionKind.OGcd, 30);
    public static readonly ActionRef AeroIIInGreen = new(34657, "Aero II in Green", ActionKind.Gcd, 35);
    public static readonly ActionRef WaterIIInBlue = new(34658, "Water II in Blue", ActionKind.Gcd, 45);
    public static readonly ActionRef WeaponMotif = new(34690, "Weapon Motif", ActionKind.Gcd, 50);
    public static readonly ActionRef HammerStamp = new(34678, "Hammer Stamp", ActionKind.Gcd, 50);
    public static readonly ActionRef SteelMuse = new(35348, "Steel Muse", ActionKind.OGcd, 50);
    public static readonly ActionRef StrikingMuse = new(34674, "Striking Muse", ActionKind.OGcd, 50);
    public static readonly ActionRef HammerMotif = new(34668, "Hammer Motif", ActionKind.Gcd, 50);
    public static readonly ActionRef ThunderIIInMagenta = new(34661, "Thunder II in Magenta", ActionKind.Gcd, 60);
    public static readonly ActionRef StoneInYellow = new(34654, "Stone in Yellow", ActionKind.Gcd, 60);
    public static readonly ActionRef BlizzardIIInCyan = new(34659, "Blizzard II in Cyan", ActionKind.Gcd, 60);
    public static readonly ActionRef ThunderInMagenta = new(34655, "Thunder in Magenta", ActionKind.Gcd, 60);
    public static readonly ActionRef BlizzardInCyan = new(34653, "Blizzard in Cyan", ActionKind.Gcd, 60);
    public static readonly ActionRef StoneIIInYellow = new(34660, "Stone II in Yellow", ActionKind.Gcd, 60);
    public static readonly ActionRef SubtractivePalette = new(34683, "Subtractive Palette", ActionKind.OGcd, 60);
    public static readonly ActionRef StarrySkyMotif = new(34669, "Starry Sky Motif", ActionKind.Gcd, 70);
    public static readonly ActionRef StarryMuse = new(34675, "Starry Muse", ActionKind.OGcd, 70);
    public static readonly ActionRef LandscapeMotif = new(34691, "Landscape Motif", ActionKind.Gcd, 70);
    public static readonly ActionRef ScenicMuse = new(35349, "Scenic Muse", ActionKind.OGcd, 70);
    public static readonly ActionRef HolyInWhite = new(34662, "Holy in White", ActionKind.Gcd, 80);
    public static readonly ActionRef HammerBrush = new(34679, "Hammer Brush", ActionKind.Gcd, 86);
    public static readonly ActionRef PolishingHammer = new(34680, "Polishing Hammer", ActionKind.Gcd, 86);
    public static readonly ActionRef TemperaGrassa = new(34686, "Tempera Grassa", ActionKind.OGcd, 88);
    public static readonly ActionRef CometInBlack = new(34663, "Comet in Black", ActionKind.Gcd, 90);
    public static readonly ActionRef RainbowDrip = new(34688, "Rainbow Drip", ActionKind.Gcd, 92);
    public static readonly ActionRef RetributionOfTheMadeen = new(34677, "Retribution of the Madeen", ActionKind.OGcd, 96);
    public static readonly ActionRef FangedMuse = new(34673, "Fanged Muse", ActionKind.OGcd, 96);
    public static readonly ActionRef ClawedMuse = new(34672, "Clawed Muse", ActionKind.OGcd, 96);
    public static readonly ActionRef MawMotif = new(34667, "Maw Motif", ActionKind.Gcd, 96);
    public static readonly ActionRef ClawMotif = new(34666, "Claw Motif", ActionKind.Gcd, 96);
    public static readonly ActionRef StarPrism = new(34681, "Star Prism", ActionKind.Gcd, 100);
    public static readonly ActionRef StarPrism2 = new(34682, "Star Prism II", ActionKind.Gcd, 100);
    public static readonly ActionRef Addle = new(7560, "Addle", ActionKind.OGcd, 8);
    public static readonly ActionRef Sleep = new(25880, "Sleep", ActionKind.Gcd, 10);
    public static readonly ActionRef LucidDreaming = new(7562, "Lucid Dreaming", ActionKind.OGcd, 14);
    public static readonly ActionRef Swiftcast = new(7561, "Swiftcast", ActionKind.OGcd, 18);
    public static readonly ActionRef Surecast = new(7559, "Surecast", ActionKind.OGcd, 44);

    public static readonly StatusRef Aetherhues = new(3675, "Aetherhues");
    public static readonly StatusRef AetherhuesII = new(3676, "Aetherhues II");
    public static readonly StatusRef TemperaCoatBuff = new(3686, "Tempera Coat");
    public static readonly StatusRef TemperaGrassaBuff = new(3687, "Tempera Grassa");
    public static readonly StatusRef SmudgeBuff = new(3684, "Smudge");
    public static readonly StatusRef HammerTime = new(3680, "Hammer Time");
    public static readonly StatusRef SubtractivePaletteBuff = new(3674, "Subtractive Palette");
    public static readonly StatusRef MonochromeTones = new(3691, "Monochrome Tones");
    public static readonly StatusRef StarryMuseBuff = new(3685, "Starry Muse");
    public static readonly StatusRef SubtractiveSpectrum = new(3690, "Subtractive Spectrum");
    public static readonly StatusRef Hyperphantasia = new(3688, "Hyperphantasia");
    public static readonly StatusRef Starstruck = new(3681, "Starstruck");
    public static readonly StatusRef RainbowBright = new(3679, "Rainbow Bright");
    public static readonly StatusRef AddleBuff = new(1203, "Addle");
    public static readonly StatusRef SurecastBuff = new(160, "Surecast");
    public static readonly StatusRef LucidDreamingBuff = new(1204, "Lucid Dreaming");
    public static readonly StatusRef SwiftcastBuff = new(167, "Swiftcast");

    public static readonly IReadOnlyList<ActionRef> All =
    [
        FireInRed, AeroInGreen, TemperaCoat, WaterInBlue,
        Smudge, FireIIInRed, WingedMuse, LivingMuse,
        CreatureMotif, WingMotif, MogOfTheAges, PomMotif,
        PomMuse, AeroIIInGreen, WaterIIInBlue, WeaponMotif,
        HammerStamp, SteelMuse, StrikingMuse, HammerMotif,
        ThunderIIInMagenta, StoneInYellow, BlizzardIIInCyan, ThunderInMagenta,
        BlizzardInCyan, StoneIIInYellow, SubtractivePalette, StarrySkyMotif,
        StarryMuse, LandscapeMotif, ScenicMuse, HolyInWhite,
        HammerBrush, PolishingHammer, TemperaGrassa, CometInBlack,
        RainbowDrip, RetributionOfTheMadeen, FangedMuse, ClawedMuse,
        MawMotif, ClawMotif, StarPrism, StarPrism2,
        Addle, Sleep, LucidDreaming, Swiftcast,
        Surecast,
    ];

    public static readonly IReadOnlyList<StatusRef> AllStatuses =
    [
        Aetherhues, AetherhuesII, TemperaCoatBuff, TemperaGrassaBuff,
        SmudgeBuff, HammerTime, SubtractivePaletteBuff, MonochromeTones,
        StarryMuseBuff, SubtractiveSpectrum, Hyperphantasia, Starstruck,
        RainbowBright, AddleBuff, SurecastBuff, LucidDreamingBuff,
        SwiftcastBuff,
    ];
}
