using TwoButton.Core.Model;

namespace TwoButton.Core.Jobs.Machinist;

/// <summary>
/// Machinist action and status ids.
/// <para>
/// Generated by <c>tools/generate_action_tables.py</c> from BossMod's ActionQueue
/// definitions (BSD 3-Clause), which are regenerated from the game's own data each
/// patch. Do not edit by hand - rerun the generator instead.
/// </para>
/// <para>
/// Ids are still verified against the game's Action and Status sheets at startup and
/// repaired by name on a mismatch, so a patch that shuffles them is corrected rather
/// than mis-cast.
/// </para>
/// </summary>
public static class MachinistActions
{
    public static readonly ActionRef SplitShot = new(2866, "Split Shot", ActionKind.Gcd, 1);
    public static readonly ActionRef SlugShot = new(2868, "Slug Shot", ActionKind.Gcd, 2);
    public static readonly ActionRef HotShot = new(2872, "Hot Shot", ActionKind.Gcd, 4);
    public static readonly ActionRef Reassemble = new(2876, "Reassemble", ActionKind.OGcd, 10);
    public static readonly ActionRef GaussRound = new(2874, "Gauss Round", ActionKind.OGcd, 15);
    public static readonly ActionRef SpreadShot = new(2870, "Spread Shot", ActionKind.Gcd, 18);
    public static readonly ActionRef CleanShot = new(2873, "Clean Shot", ActionKind.Gcd, 26);
    public static readonly ActionRef Hypercharge = new(17209, "Hypercharge", ActionKind.OGcd, 30);
    public static readonly ActionRef HeatBlast = new(7410, "Heat Blast", ActionKind.Gcd, 35);
    public static readonly ActionRef RookAutoturret = new(2864, "Rook Autoturret", ActionKind.OGcd, 40);
    public static readonly ActionRef RookOverdrive = new(7415, "Rook Overdrive", ActionKind.OGcd, 40);
    public static readonly ActionRef Detonator = new(16766, "Detonator", ActionKind.OGcd, 45);
    public static readonly ActionRef Wildfire = new(2878, "Wildfire", ActionKind.OGcd, 45);
    public static readonly ActionRef Ricochet = new(2890, "Ricochet", ActionKind.OGcd, 50);
    public static readonly ActionRef AutoCrossbow = new(16497, "Au to Crossbow", ActionKind.Gcd, 52);
    public static readonly ActionRef HeatedSplitShot = new(7411, "Heated Split Shot", ActionKind.Gcd, 54);
    public static readonly ActionRef Tactician = new(16889, "Tactician", ActionKind.OGcd, 56);
    public static readonly ActionRef Drill = new(16498, "Drill", ActionKind.Gcd, 58);
    public static readonly ActionRef HeatedSlugShot = new(7412, "Heated Slug Shot", ActionKind.Gcd, 60);
    public static readonly ActionRef Dismantle = new(2887, "Dismantle", ActionKind.OGcd, 62);
    public static readonly ActionRef HeatedCleanShot = new(7413, "Heated Clean Shot", ActionKind.Gcd, 64);
    public static readonly ActionRef BarrelStabilizer = new(7414, "Barrel Stabilizer", ActionKind.OGcd, 66);
    public static readonly ActionRef BlazingShot = new(36978, "Blazing Shot", ActionKind.Gcd, 68);
    public static readonly ActionRef Flamethrower = new(7418, "Flamethrower", ActionKind.Gcd, 70);
    public static readonly ActionRef Bioblaster = new(16499, "Bioblaster", ActionKind.Gcd, 72);
    public static readonly ActionRef AirAnchor = new(16500, "Air Anchor", ActionKind.Gcd, 76);
    public static readonly ActionRef AutomatonQueen = new(16501, "Automaton Queen", ActionKind.OGcd, 80);
    public static readonly ActionRef QueenOverdrive = new(16502, "Queen Overdrive", ActionKind.OGcd, 80);
    public static readonly ActionRef Scattergun = new(25786, "Scattergun", ActionKind.Gcd, 82);
    public static readonly ActionRef ChainSaw = new(25788, "Cha in Saw", ActionKind.Gcd, 90);
    public static readonly ActionRef DoubleCheck = new(36979, "Double Check", ActionKind.OGcd, 92);
    public static readonly ActionRef Checkmate = new(36980, "Checkmate", ActionKind.OGcd, 92);
    public static readonly ActionRef Excavator = new(36981, "Excavator", ActionKind.Gcd, 96);
    public static readonly ActionRef FullMetalField = new(36982, "Full Metal Field", ActionKind.Gcd, 100);
    public static readonly ActionRef LegGraze = new(7554, "Leg Graze", ActionKind.OGcd, 6);
    public static readonly ActionRef SecondWind = new(7541, "Second Wind", ActionKind.OGcd, 8);
    public static readonly ActionRef FootGraze = new(7553, "Foot Graze", ActionKind.OGcd, 10);
    public static readonly ActionRef Peloton = new(7557, "Peloton", ActionKind.OGcd, 20);
    public static readonly ActionRef HeadGraze = new(7551, "Head Graze", ActionKind.OGcd, 24);
    public static readonly ActionRef ArmsLength = new(7548, "Arms Length", ActionKind.OGcd, 32);

    public static readonly StatusRef Reassembled = new(851, "Reassembled");
    public static readonly StatusRef Overheated = new(2688, "Overheated");
    public static readonly StatusRef WildfirePlayer = new(1946, "Wildfire Player");
    public static readonly StatusRef WildfireTarget = new(861, "Wildfire Target");
    public static readonly StatusRef Dismantled = new(860, "Dismantled");
    public static readonly StatusRef Hypercharged = new(3864, "Hypercharged");
    public static readonly StatusRef FlamethrowerBuff = new(1205, "Flamethrower");
    public static readonly StatusRef ExcavatorReady = new(3865, "Excavator Ready");
    public static readonly StatusRef FullMetalMachinist = new(3866, "Full Metal Machinist");
    public static readonly StatusRef TacticianBuff = new(1951, "Tactician");
    public static readonly StatusRef BioblasterBuff = new(1866, "Bioblaster");
    public static readonly StatusRef PelotonBuff = new(1199, "Peloton");
    public static readonly StatusRef HeatPvP = new(3148, "Heat Pv P");
    public static readonly StatusRef OverheatedPvP = new(3149, "Overheated Pv P");
    public static readonly StatusRef DrillPrimed = new(3150, "Drill Primed");
    public static readonly StatusRef BioblasterPrimed = new(3151, "Bioblaster Primed");
    public static readonly StatusRef AirAnchorPrimed = new(3152, "Air Anchor Primed");
    public static readonly StatusRef ChainSawPrimed = new(3153, "Cha in Saw Primed");
    public static readonly StatusRef AnalysisPvP = new(3158, "Analysis Pv P");
    public static readonly StatusRef WildfirePlayerPvP = new(2018, "Wildfire Player Pv P");
    public static readonly StatusRef WildfireTargetPvP = new(1323, "Wildfire Target Pv P");
    public static readonly StatusRef DervishEquippedPvP = new(4489, "Dervish Equipped Pv P");
    public static readonly StatusRef BraveryEquippedPvP = new(4490, "Bravery Equipped Pv P");
    public static readonly StatusRef EagleEyeShotEquippedPvP = new(4491, "Eagle Eye Shot Equipped Pv P");
    public static readonly StatusRef GuardPvP = new(3054, "Guard Pv P");
    public static readonly StatusRef SprintPvP = new(1342, "Sprint Pv P");
    public static readonly StatusRef SilencePvP = new(1347, "Silence Pv P");
    public static readonly StatusRef BindPvP = new(1345, "Bind Pv P");
    public static readonly StatusRef StunPvP = new(1343, "Stun Pv P");
    public static readonly StatusRef HalfAsleepPvP = new(3022, "Half Asleep Pv P");
    public static readonly StatusRef SleepPvP = new(1348, "Sleep Pv P");
    public static readonly StatusRef DeepFreezePvP = new(3219, "Deep Freeze Pv P");
    public static readonly StatusRef HeavyPvP = new(1344, "Heavy Pv P");
    public static readonly StatusRef UnguardedPvP = new(3021, "Unguarded Pv P");

    public static readonly IReadOnlyList<ActionRef> All =
    [
        SplitShot, SlugShot, HotShot, Reassemble,
        GaussRound, SpreadShot, CleanShot, Hypercharge,
        HeatBlast, RookAutoturret, RookOverdrive, Detonator,
        Wildfire, Ricochet, AutoCrossbow, HeatedSplitShot,
        Tactician, Drill, HeatedSlugShot, Dismantle,
        HeatedCleanShot, BarrelStabilizer, BlazingShot, Flamethrower,
        Bioblaster, AirAnchor, AutomatonQueen, QueenOverdrive,
        Scattergun, ChainSaw, DoubleCheck, Checkmate,
        Excavator, FullMetalField, LegGraze, SecondWind,
        FootGraze, Peloton, HeadGraze, ArmsLength,
    ];

    public static readonly IReadOnlyList<StatusRef> AllStatuses =
    [
        Reassembled, Overheated, WildfirePlayer, WildfireTarget,
        Dismantled, Hypercharged, FlamethrowerBuff, ExcavatorReady,
        FullMetalMachinist, TacticianBuff, BioblasterBuff, PelotonBuff,
        HeatPvP, OverheatedPvP, DrillPrimed, BioblasterPrimed,
        AirAnchorPrimed, ChainSawPrimed, AnalysisPvP, WildfirePlayerPvP,
        WildfireTargetPvP, DervishEquippedPvP, BraveryEquippedPvP, EagleEyeShotEquippedPvP,
        GuardPvP, SprintPvP, SilencePvP, BindPvP,
        StunPvP, HalfAsleepPvP, SleepPvP, DeepFreezePvP,
        HeavyPvP, UnguardedPvP,
    ];
}
