using TwoButton.Core.Model;

namespace TwoButton.Core.Jobs.BlackMage;

/// <summary>
/// BlackMage action and status ids.
/// <para>
/// Generated by <c>tools/generate_action_tables.py</c> from BossMod's ActionQueue
/// definitions (BSD 3-Clause), which are regenerated from the game's own data each
/// patch. Do not edit by hand - rerun the generator instead.
/// </para>
/// <para>
/// Ids are still verified against the game's Action and Status sheets at startup and
/// repaired by name on a mismatch, so a patch that shuffles them is corrected rather
/// than mis-cast.
/// </para>
/// </summary>
public static class BlackMageActions
{
    public static readonly ActionRef Blizzard1 = new(142, "Blizzard", ActionKind.Gcd, 1);
    public static readonly ActionRef Fire1 = new(141, "Fire", ActionKind.Gcd, 2);
    public static readonly ActionRef Transpose = new(149, "Transpose", ActionKind.OGcd, 4);
    public static readonly ActionRef Thunder1 = new(144, "Thunder", ActionKind.Gcd, 6);
    public static readonly ActionRef Blizzard2 = new(25793, "Blizzard II", ActionKind.Gcd, 12);
    public static readonly ActionRef Scathe = new(156, "Scathe", ActionKind.Gcd, 15);
    public static readonly ActionRef Fire2 = new(147, "Fire II", ActionKind.Gcd, 18);
    public static readonly ActionRef Thunder2 = new(7447, "Thunder II", ActionKind.Gcd, 26);
    public static readonly ActionRef Manaward = new(157, "Manaward", ActionKind.OGcd, 30);
    public static readonly ActionRef Manafont = new(158, "Manafont", ActionKind.OGcd, 30);
    public static readonly ActionRef UmbralSoul = new(16506, "Umbral Soul", ActionKind.Gcd, 35);
    public static readonly ActionRef Fire3 = new(152, "Fire III", ActionKind.Gcd, 35);
    public static readonly ActionRef Blizzard3 = new(154, "Blizzard III", ActionKind.Gcd, 35);
    public static readonly ActionRef Freeze = new(159, "Freeze", ActionKind.Gcd, 40);
    public static readonly ActionRef Thunder3 = new(153, "Thunder III", ActionKind.Gcd, 45);
    public static readonly ActionRef Flare = new(162, "Flare", ActionKind.Gcd, 50);
    public static readonly ActionRef AetherialManipulation = new(155, "Aetherial Manipulation", ActionKind.OGcd, 50);
    public static readonly ActionRef LeyLines = new(3573, "Ley Lines", ActionKind.OGcd, 52);
    public static readonly ActionRef Blizzard4 = new(3576, "Blizzard IV", ActionKind.Gcd, 58);
    public static readonly ActionRef Fire4 = new(3577, "Fire IV", ActionKind.Gcd, 60);
    public static readonly ActionRef BetweenTheLines = new(7419, "Between the Lines", ActionKind.OGcd, 62);
    public static readonly ActionRef Thunder4 = new(7420, "Thunder IV", ActionKind.Gcd, 64);
    public static readonly ActionRef Triplecast = new(7421, "Triplecast", ActionKind.OGcd, 66);
    public static readonly ActionRef Foul = new(7422, "Foul", ActionKind.Gcd, 70);
    public static readonly ActionRef Despair = new(16505, "Despair", ActionKind.Gcd, 72);
    public static readonly ActionRef Xenoglossy = new(16507, "Xenoglossy", ActionKind.Gcd, 80);
    public static readonly ActionRef HighBlizzard2 = new(25795, "High Blizzard II", ActionKind.Gcd, 82);
    public static readonly ActionRef HighFire2 = new(25794, "High Fire II", ActionKind.Gcd, 82);
    public static readonly ActionRef Amplifier = new(25796, "Amplifier", ActionKind.OGcd, 86);
    public static readonly ActionRef Paradox = new(25797, "Paradox", ActionKind.Gcd, 90);
    public static readonly ActionRef HighThunder = new(36986, "High Thunder", ActionKind.Gcd, 92);
    public static readonly ActionRef HighThunder2 = new(36987, "High Thunder II", ActionKind.Gcd, 92);
    public static readonly ActionRef Retrace = new(36988, "Retrace", ActionKind.OGcd, 96);
    public static readonly ActionRef FlareStar = new(36989, "Flare Star", ActionKind.Gcd, 100);
    public static readonly ActionRef Addle = new(7560, "Addle", ActionKind.OGcd, 8);
    public static readonly ActionRef Sleep = new(25880, "Sleep", ActionKind.Gcd, 10);
    public static readonly ActionRef LucidDreaming = new(7562, "Lucid Dreaming", ActionKind.OGcd, 14);
    public static readonly ActionRef Swiftcast = new(7561, "Swiftcast", ActionKind.OGcd, 18);
    public static readonly ActionRef Surecast = new(7559, "Surecast", ActionKind.OGcd, 44);

    public static readonly StatusRef ManawardBuff = new(168, "Manaward");
    public static readonly StatusRef Thunder = new(161, "Thunder");
    public static readonly StatusRef ThunderII = new(162, "Thunder II");
    public static readonly StatusRef ThunderIII = new(163, "Thunder III");
    public static readonly StatusRef ThunderIV = new(1210, "Thunder IV");
    public static readonly StatusRef LeyLinesBuff = new(737, "Ley Lines");
    public static readonly StatusRef CircleOfPower = new(738, "Circle of Power");
    public static readonly StatusRef TriplecastBuff = new(1211, "Triplecast");
    public static readonly StatusRef Firestarter = new(165, "Firestarter");
    public static readonly StatusRef Thunderhead = new(3870, "Thunderhead");
    public static readonly StatusRef HighThunderBuff = new(3871, "High Thunder");
    public static readonly StatusRef HighThunderII = new(3872, "High Thunder II");
    public static readonly StatusRef AddleBuff = new(1203, "Addle");
    public static readonly StatusRef SurecastBuff = new(160, "Surecast");
    public static readonly StatusRef LucidDreamingBuff = new(1204, "Lucid Dreaming");
    public static readonly StatusRef SwiftcastBuff = new(167, "Swiftcast");

    public static readonly IReadOnlyList<ActionRef> All =
    [
        Blizzard1, Fire1, Transpose, Thunder1,
        Blizzard2, Scathe, Fire2, Thunder2,
        Manaward, Manafont, UmbralSoul, Fire3,
        Blizzard3, Freeze, Thunder3, Flare,
        AetherialManipulation, LeyLines, Blizzard4, Fire4,
        BetweenTheLines, Thunder4, Triplecast, Foul,
        Despair, Xenoglossy, HighBlizzard2, HighFire2,
        Amplifier, Paradox, HighThunder, HighThunder2,
        Retrace, FlareStar, Addle, Sleep,
        LucidDreaming, Swiftcast, Surecast,
    ];

    public static readonly IReadOnlyList<StatusRef> AllStatuses =
    [
        ManawardBuff, Thunder, ThunderII, ThunderIII,
        ThunderIV, LeyLinesBuff, CircleOfPower, TriplecastBuff,
        Firestarter, Thunderhead, HighThunderBuff, HighThunderII,
        AddleBuff, SurecastBuff, LucidDreamingBuff, SwiftcastBuff,
    ];
}
