using TwoButton.Core.Model;

namespace TwoButton.Core.Jobs.Monk;

/// <summary>
/// Monk action and status ids.
/// <para>
/// Generated by <c>tools/generate_action_tables.py</c> from BossMod's ActionQueue
/// definitions (BSD 3-Clause), which are regenerated from the game's own data each
/// patch. Do not edit by hand - rerun the generator instead.
/// </para>
/// <para>
/// Ids are still verified against the game's Action and Status sheets at startup and
/// repaired by name on a mismatch, so a patch that shuffles them is corrected rather
/// than mis-cast.
/// </para>
/// </summary>
public static class MonkActions
{
    public static readonly ActionRef Bootshine = new(53, "Bootshine", ActionKind.OGcd, 1);
    public static readonly ActionRef TrueStrike = new(54, "True Strike", ActionKind.OGcd, 4);
    public static readonly ActionRef SnapPunch = new(56, "Snap Punch", ActionKind.OGcd, 6);
    public static readonly ActionRef SteeledMeditation = new(36940, "Steeled Meditation", ActionKind.OGcd, 15);
    public static readonly ActionRef TwinSnakes = new(61, "Twin Snakes", ActionKind.OGcd, 18);
    public static readonly ActionRef ArmOfTheDestroyer = new(62, "Arm Of The Destroyer", ActionKind.OGcd, 26);
    public static readonly ActionRef Demolish = new(66, "Demolish", ActionKind.OGcd, 30);
    public static readonly ActionRef Rockbreaker = new(70, "Rockbreaker", ActionKind.OGcd, 30);
    public static readonly ActionRef InspiritedMeditation = new(36941, "Inspirited Meditation", ActionKind.OGcd, 40);
    public static readonly ActionRef FourPointFury = new(16473, "Four Point Fury", ActionKind.OGcd, 45);
    public static readonly ActionRef DragonKick = new(74, "Dragon Kick", ActionKind.OGcd, 50);
    public static readonly ActionRef FormShift = new(4262, "Form Shift", ActionKind.OGcd, 52);
    public static readonly ActionRef ForbiddenMeditation = new(36942, "Forbidden Meditation", ActionKind.OGcd, 54);
    public static readonly ActionRef TornadoKick = new(3543, "Tornado Kick", ActionKind.OGcd, 60);
    public static readonly ActionRef FlintStrike = new(25882, "Flint Strike", ActionKind.OGcd, 60);
    public static readonly ActionRef CelestialRevolution = new(25765, "Celestial Revolution", ActionKind.OGcd, 60);
    public static readonly ActionRef MasterfulBlitz = new(25764, "Masterful Blitz", ActionKind.OGcd, 60);
    public static readonly ActionRef ElixirField = new(3545, "Elixir Field", ActionKind.OGcd, 60);
    public static readonly ActionRef EnlightenedMeditation = new(36943, "Enlightened Meditation", ActionKind.OGcd, 74);
    public static readonly ActionRef SixSidedStar = new(16476, "Six Sided Star", ActionKind.OGcd, 80);
    public static readonly ActionRef ShadowOfTheDestroyer = new(25767, "Shadow Of The Destroyer", ActionKind.OGcd, 82);
    public static readonly ActionRef RisingPhoenix = new(25768, "Rising Phoenix", ActionKind.OGcd, 86);
    public static readonly ActionRef PhantomRush = new(25769, "Phantom Rush", ActionKind.OGcd, 90);
    public static readonly ActionRef LeapingOpo = new(36945, "Leaping Opo", ActionKind.OGcd, 92);
    public static readonly ActionRef RisingRaptor = new(36946, "Rising Raptor", ActionKind.OGcd, 92);
    public static readonly ActionRef PouncingCoeurl = new(36947, "Pouncing Coeurl", ActionKind.OGcd, 92);
    public static readonly ActionRef ElixirBurst = new(36948, "Elixir Burst", ActionKind.OGcd, 92);
    public static readonly ActionRef WindsReply = new(36949, "Winds Reply", ActionKind.OGcd, 96);
    public static readonly ActionRef FiresReply = new(36950, "Fires Reply", ActionKind.OGcd, 100);
    public static readonly ActionRef SteelPeak = new(25761, "Steel Peak", ActionKind.OGcd, 15);
    public static readonly ActionRef Thunderclap = new(25762, "Thunderclap", ActionKind.OGcd, 35);
    public static readonly ActionRef HowlingFist = new(25763, "Howling Fist", ActionKind.OGcd, 40);
    public static readonly ActionRef Mantra = new(65, "Mantra", ActionKind.OGcd, 42);
    public static readonly ActionRef PerfectBalance = new(69, "Perfect Balance", ActionKind.OGcd, 50);
    public static readonly ActionRef ForbiddenChakra = new(3547, "Forbidden Chakra", ActionKind.OGcd, 54);
    public static readonly ActionRef RiddleOfEarth = new(7394, "Riddle Of Earth", ActionKind.OGcd, 64);
    public static readonly ActionRef EarthsReply = new(36944, "Earths Reply", ActionKind.OGcd, 64);
    public static readonly ActionRef RiddleOfFire = new(7395, "Riddle Of Fire", ActionKind.OGcd, 68);
    public static readonly ActionRef Brotherhood = new(7396, "Brotherhood", ActionKind.OGcd, 70);
    public static readonly ActionRef RiddleOfWind = new(25766, "Riddle Of Wind", ActionKind.OGcd, 72);
    public static readonly ActionRef Enlightenment = new(16474, "Enlightenment", ActionKind.OGcd, 74);
    public static readonly ActionRef SecondWind = new(7541, "Second Wind", ActionKind.OGcd, 8);
    public static readonly ActionRef LegSweep = new(7863, "Leg Sweep", ActionKind.OGcd, 10);
    public static readonly ActionRef Bloodbath = new(7542, "Bloodbath", ActionKind.OGcd, 12);
    public static readonly ActionRef Feint = new(7549, "Feint", ActionKind.OGcd, 22);
    public static readonly ActionRef ArmsLength = new(7548, "Arms Length", ActionKind.OGcd, 32);
    public static readonly ActionRef TrueNorth = new(7546, "True North", ActionKind.OGcd, 50);

    public static readonly StatusRef RaptorForm = new(108, "Raptor Form");
    public static readonly StatusRef CoeurlForm = new(109, "Coeurl Form");
    public static readonly StatusRef MeditativeBrotherhood = new(1182, "Meditative Brotherhood");
    public static readonly StatusRef BrotherhoodBuff = new(1185, "Brotherhood");
    public static readonly StatusRef RiddleOfFireBuff = new(1181, "Riddle Of Fire");
    public static readonly StatusRef FiresRumination = new(3843, "Fires Rumination");
    public static readonly StatusRef RiddleOfWindBuff = new(2687, "Riddle Of Wind");
    public static readonly StatusRef WindsRumination = new(3842, "Winds Rumination");
    public static readonly StatusRef MantraBuff = new(102, "Mantra");
    public static readonly StatusRef RiddleOfEarthBuff = new(1179, "Riddle Of Earth");
    public static readonly StatusRef EarthsRumination = new(3841, "Earths Rumination");
    public static readonly StatusRef FormlessFist = new(2513, "Formless Fist");
    public static readonly StatusRef SixSidedStarBuff = new(2514, "Six Sided Star");
    public static readonly StatusRef OpoOpoForm = new(107, "Opo Opo Form");
    public static readonly StatusRef PerfectBalanceBuff = new(110, "Perfect Balance");
    public static readonly StatusRef Stun = new(2, "Stun");
    public static readonly StatusRef FeintBuff = new(1195, "Feint");
    public static readonly StatusRef TrueNorthBuff = new(1250, "True North");

    public static readonly IReadOnlyList<ActionRef> All =
    [
        Bootshine, TrueStrike, SnapPunch, SteeledMeditation,
        TwinSnakes, ArmOfTheDestroyer, Demolish, Rockbreaker,
        InspiritedMeditation, FourPointFury, DragonKick, FormShift,
        ForbiddenMeditation, TornadoKick, FlintStrike, CelestialRevolution,
        MasterfulBlitz, ElixirField, EnlightenedMeditation, SixSidedStar,
        ShadowOfTheDestroyer, RisingPhoenix, PhantomRush, LeapingOpo,
        RisingRaptor, PouncingCoeurl, ElixirBurst, WindsReply,
        FiresReply, SteelPeak, Thunderclap, HowlingFist,
        Mantra, PerfectBalance, ForbiddenChakra, RiddleOfEarth,
        EarthsReply, RiddleOfFire, Brotherhood, RiddleOfWind,
        Enlightenment, SecondWind, LegSweep, Bloodbath,
        Feint, ArmsLength, TrueNorth,
    ];

    public static readonly IReadOnlyList<StatusRef> AllStatuses =
    [
        RaptorForm, CoeurlForm, MeditativeBrotherhood, BrotherhoodBuff,
        RiddleOfFireBuff, FiresRumination, RiddleOfWindBuff, WindsRumination,
        MantraBuff, RiddleOfEarthBuff, EarthsRumination, FormlessFist,
        SixSidedStarBuff, OpoOpoForm, PerfectBalanceBuff, Stun,
        FeintBuff, TrueNorthBuff,
    ];
}
