using TwoButton.Core.Model;

namespace TwoButton.Core.Jobs.Bard;

/// <summary>
/// Bard action and status ids.
/// <para>
/// Generated by <c>tools/generate_action_tables.py</c> from BossMod's ActionQueue
/// definitions (BSD 3-Clause), which are regenerated from the game's own data each
/// patch. Do not edit by hand - rerun the generator instead.
/// </para>
/// <para>
/// Ids are still verified against the game's Action and Status sheets at startup and
/// repaired by name on a mismatch, so a patch that shuffles them is corrected rather
/// than mis-cast.
/// </para>
/// </summary>
public static class BardActions
{
    public static readonly ActionRef HeavyShot = new(97, "Heavy Shot", ActionKind.Gcd, 1);
    public static readonly ActionRef StraightShot = new(98, "Straight Shot", ActionKind.Gcd, 2);
    public static readonly ActionRef RagingStrikes = new(101, "Raging Strikes", ActionKind.OGcd, 4);
    public static readonly ActionRef VenomousBite = new(100, "Venomous Bite", ActionKind.Gcd, 6);
    public static readonly ActionRef Bloodletter = new(110, "Bloodletter", ActionKind.OGcd, 12);
    public static readonly ActionRef RepellingShot = new(112, "Repelling Shot", ActionKind.OGcd, 15);
    public static readonly ActionRef QuickNock = new(106, "Quick Nock", ActionKind.Gcd, 18);
    public static readonly ActionRef WideVolley = new(36974, "Wide Volley", ActionKind.Gcd, 25);
    public static readonly ActionRef MagesBallad = new(114, "Mages Ballad", ActionKind.OGcd, 30);
    public static readonly ActionRef Windbite = new(113, "Windbite", ActionKind.Gcd, 30);
    public static readonly ActionRef WardensPaean = new(3561, "Wardens Paean", ActionKind.OGcd, 35);
    public static readonly ActionRef Barrage = new(107, "Barrage", ActionKind.OGcd, 38);
    public static readonly ActionRef ArmysPaeon = new(116, "Armys Paeon", ActionKind.OGcd, 40);
    public static readonly ActionRef RainOfDeath = new(117, "Rain Of Death", ActionKind.OGcd, 45);
    public static readonly ActionRef BattleVoice = new(118, "Battle Voice", ActionKind.OGcd, 50);
    public static readonly ActionRef WanderersMinuet = new(3559, "Wanderers Minuet", ActionKind.OGcd, 52);
    public static readonly ActionRef PitchPerfect = new(7404, "Pitch Perfect", ActionKind.OGcd, 52);
    public static readonly ActionRef EmpyrealArrow = new(3558, "Empyreal Arrow", ActionKind.OGcd, 54);
    public static readonly ActionRef IronJaws = new(3560, "Iron Jaws", ActionKind.Gcd, 56);
    public static readonly ActionRef Sidewinder = new(3562, "Sidewinder", ActionKind.OGcd, 60);
    public static readonly ActionRef Troubadour = new(7405, "Troubadour", ActionKind.OGcd, 62);
    public static readonly ActionRef Stormbite = new(7407, "Stormbite", ActionKind.Gcd, 64);
    public static readonly ActionRef CausticBite = new(7406, "Caustic Bite", ActionKind.Gcd, 64);
    public static readonly ActionRef NaturesMinne = new(7408, "Natures Minne", ActionKind.OGcd, 66);
    public static readonly ActionRef RefulgentArrow = new(7409, "Refulgent Arrow", ActionKind.Gcd, 70);
    public static readonly ActionRef Shadowbite = new(16494, "Shadowbite", ActionKind.Gcd, 72);
    public static readonly ActionRef BurstShot = new(16495, "Burst Shot", ActionKind.Gcd, 76);
    public static readonly ActionRef ApexArrow = new(16496, "Apex Arrow", ActionKind.Gcd, 80);
    public static readonly ActionRef Ladonsbite = new(25783, "Ladonsbite", ActionKind.Gcd, 82);
    public static readonly ActionRef BlastArrow = new(25784, "Blast Arrow", ActionKind.Gcd, 86);
    public static readonly ActionRef RadiantFinale = new(25785, "Radiant Finale", ActionKind.OGcd, 90);
    public static readonly ActionRef HeartbreakShot = new(36975, "Heartbreak Shot", ActionKind.OGcd, 92);
    public static readonly ActionRef ResonantArrow = new(36976, "Resonant Arrow", ActionKind.Gcd, 96);
    public static readonly ActionRef RadiantEncore = new(36977, "Radiant Encore", ActionKind.Gcd, 100);
    public static readonly ActionRef LegGraze = new(7554, "Leg Graze", ActionKind.OGcd, 6);
    public static readonly ActionRef SecondWind = new(7541, "Second Wind", ActionKind.OGcd, 8);
    public static readonly ActionRef FootGraze = new(7553, "Foot Graze", ActionKind.OGcd, 10);
    public static readonly ActionRef Peloton = new(7557, "Peloton", ActionKind.OGcd, 20);
    public static readonly ActionRef HeadGraze = new(7551, "Head Graze", ActionKind.OGcd, 24);
    public static readonly ActionRef ArmsLength = new(7548, "Arms Length", ActionKind.OGcd, 32);

    public static readonly StatusRef RagingStrikesBuff = new(125, "Raging Strikes");
    public static readonly StatusRef ArmsLengthBuff = new(1209, "Arms Length");
    public static readonly StatusRef BarrageBuff = new(128, "Barrage");
    public static readonly StatusRef BattleVoiceBuff = new(141, "Battle Voice");
    public static readonly StatusRef HawksEye = new(3861, "Hawks Eye");
    public static readonly StatusRef CausticBiteBuff = new(1200, "Caustic Bite");
    public static readonly StatusRef StormbiteBuff = new(1201, "Stormbite");
    public static readonly StatusRef BlastArrowReady = new(2692, "Blast Arrow Ready");
    public static readonly StatusRef RadiantFinaleBuff = new(2964, "Radiant Finale");
    public static readonly StatusRef RadiantFinaleVisual = new(2722, "Radiant Finale Visual");
    public static readonly StatusRef VenomousBiteBuff = new(124, "Venomous Bite");
    public static readonly StatusRef WindbiteBuff = new(129, "Windbite");
    public static readonly StatusRef NaturesMinneBuff = new(1202, "Natures Minne");
    public static readonly StatusRef WardensPaeanBuff = new(866, "Wardens Paean");
    public static readonly StatusRef TroubadourBuff = new(1934, "Troubadour");
    public static readonly StatusRef Bind = new(13, "Bind");
    public static readonly StatusRef ArmysMuse = new(1932, "Armys Muse");
    public static readonly StatusRef ArmysEthos = new(1933, "Armys Ethos");
    public static readonly StatusRef ResonantArrowReady = new(3862, "Resonant Arrow Ready");
    public static readonly StatusRef RadiantEncoreReady = new(3863, "Radiant Encore Ready");
    public static readonly StatusRef PelotonBuff = new(1199, "Peloton");

    public static readonly IReadOnlyList<ActionRef> All =
    [
        HeavyShot, StraightShot, RagingStrikes, VenomousBite,
        Bloodletter, RepellingShot, QuickNock, WideVolley,
        MagesBallad, Windbite, WardensPaean, Barrage,
        ArmysPaeon, RainOfDeath, BattleVoice, WanderersMinuet,
        PitchPerfect, EmpyrealArrow, IronJaws, Sidewinder,
        Troubadour, Stormbite, CausticBite, NaturesMinne,
        RefulgentArrow, Shadowbite, BurstShot, ApexArrow,
        Ladonsbite, BlastArrow, RadiantFinale, HeartbreakShot,
        ResonantArrow, RadiantEncore, LegGraze, SecondWind,
        FootGraze, Peloton, HeadGraze, ArmsLength,
    ];

    public static readonly IReadOnlyList<StatusRef> AllStatuses =
    [
        RagingStrikesBuff, ArmsLengthBuff, BarrageBuff, BattleVoiceBuff,
        HawksEye, CausticBiteBuff, StormbiteBuff, BlastArrowReady,
        RadiantFinaleBuff, RadiantFinaleVisual, VenomousBiteBuff, WindbiteBuff,
        NaturesMinneBuff, WardensPaeanBuff, TroubadourBuff, Bind,
        ArmysMuse, ArmysEthos, ResonantArrowReady, RadiantEncoreReady,
        PelotonBuff,
    ];
}
