using TwoButton.Core.Model;

namespace TwoButton.Core.Jobs.Reaper;

/// <summary>
/// Reaper action and status ids.
/// <para>
/// Generated by <c>tools/generate_action_tables.py</c> from BossMod's ActionQueue
/// definitions (BSD 3-Clause), which are regenerated from the game's own data each
/// patch. Do not edit by hand - rerun the generator instead.
/// </para>
/// <para>
/// Ids are still verified against the game's Action and Status sheets at startup and
/// repaired by name on a mismatch, so a patch that shuffles them is corrected rather
/// than mis-cast.
/// </para>
/// </summary>
public static class ReaperActions
{
    public static readonly ActionRef Slice = new(24373, "Slice", ActionKind.Gcd, 1);
    public static readonly ActionRef WaxingSlice = new(24374, "Waxing Slice", ActionKind.Gcd, 5);
    public static readonly ActionRef ShadowofDeath = new(24378, "Shadowof Death", ActionKind.Gcd, 10);
    public static readonly ActionRef Harpe = new(24386, "Harpe", ActionKind.Gcd, 15);
    public static readonly ActionRef HellsEgress = new(24402, "Hells Egress", ActionKind.OGcd, 20);
    public static readonly ActionRef HellsIngress = new(24401, "Hells Ingress", ActionKind.OGcd, 20);
    public static readonly ActionRef SpinningScythe = new(24376, "Spinning Scythe", ActionKind.Gcd, 25);
    public static readonly ActionRef InfernalSlice = new(24375, "Infernal Slice", ActionKind.Gcd, 30);
    public static readonly ActionRef WhorlofDeath = new(24379, "Whorlof Death", ActionKind.Gcd, 35);
    public static readonly ActionRef ArcaneCrest = new(24404, "Arcane Crest", ActionKind.OGcd, 40);
    public static readonly ActionRef NightmareScythe = new(24377, "Nightmare Scythe", ActionKind.Gcd, 45);
    public static readonly ActionRef BloodStalk = new(24389, "Blood Stalk", ActionKind.OGcd, 50);
    public static readonly ActionRef GrimSwathe = new(24392, "Grim Swathe", ActionKind.OGcd, 55);
    public static readonly ActionRef SoulSlice = new(24380, "Soul Slice", ActionKind.Gcd, 60);
    public static readonly ActionRef SoulScythe = new(24381, "Soul Scythe", ActionKind.Gcd, 65);
    public static readonly ActionRef UnveiledGibbet = new(24390, "Unveiled Gibbet", ActionKind.OGcd, 70);
    public static readonly ActionRef Guillotine = new(24384, "Guillotine", ActionKind.Gcd, 70);
    public static readonly ActionRef Gibbet = new(24382, "Gibbet", ActionKind.Gcd, 70);
    public static readonly ActionRef Gallows = new(24383, "Gallows", ActionKind.Gcd, 70);
    public static readonly ActionRef UnveiledGallows = new(24391, "Unveiled Gallows", ActionKind.OGcd, 70);
    public static readonly ActionRef ArcaneCircle = new(24405, "Arcane Circle", ActionKind.OGcd, 72);
    public static readonly ActionRef Regress = new(24403, "Regress", ActionKind.OGcd, 74);
    public static readonly ActionRef Gluttony = new(24393, "Gluttony", ActionKind.OGcd, 76);
    public static readonly ActionRef GrimReaping = new(24397, "Grim Reaping", ActionKind.Gcd, 80);
    public static readonly ActionRef CrossReaping = new(24396, "Cross Reaping", ActionKind.Gcd, 80);
    public static readonly ActionRef VoidReaping = new(24395, "Void Reaping", ActionKind.Gcd, 80);
    public static readonly ActionRef Enshroud = new(24394, "Enshroud", ActionKind.OGcd, 80);
    public static readonly ActionRef Soulsow = new(24387, "Soulsow", ActionKind.Gcd, 82);
    public static readonly ActionRef HarvestMoon = new(24388, "Harvest Moon", ActionKind.Gcd, 82);
    public static readonly ActionRef LemuresSlice = new(24399, "Lemures Slice", ActionKind.OGcd, 86);
    public static readonly ActionRef LemuresScythe = new(24400, "Lemures Scythe", ActionKind.OGcd, 86);
    public static readonly ActionRef PlentifulHarvest = new(24385, "Plentiful Harvest", ActionKind.Gcd, 88);
    public static readonly ActionRef Communio = new(24398, "Communio", ActionKind.Gcd, 90);
    public static readonly ActionRef Sacrificium = new(36969, "Sacrificium", ActionKind.OGcd, 92);
    public static readonly ActionRef ExecutionersGibbet = new(36970, "Executioners Gibbet", ActionKind.Gcd, 96);
    public static readonly ActionRef ExecutionersGallows = new(36971, "Executioners Gallows", ActionKind.Gcd, 96);
    public static readonly ActionRef ExecutionersGuillotine = new(36972, "Executioners Guillotine", ActionKind.Gcd, 96);
    public static readonly ActionRef Perfectio = new(36973, "Perfectio", ActionKind.Gcd, 100);
    public static readonly ActionRef SecondWind = new(7541, "Second Wind", ActionKind.OGcd, 8);
    public static readonly ActionRef LegSweep = new(7863, "Leg Sweep", ActionKind.OGcd, 10);
    public static readonly ActionRef Bloodbath = new(7542, "Bloodbath", ActionKind.OGcd, 12);
    public static readonly ActionRef Feint = new(7549, "Feint", ActionKind.OGcd, 22);
    public static readonly ActionRef ArmsLength = new(7548, "Arms Length", ActionKind.OGcd, 32);
    public static readonly ActionRef TrueNorth = new(7546, "True North", ActionKind.OGcd, 50);

    public static readonly StatusRef FeintBuff = new(1195, "Feint");
    public static readonly StatusRef TrueNorthBuff = new(1250, "True North");

    public static readonly IReadOnlyList<ActionRef> All =
    [
        Slice, WaxingSlice, ShadowofDeath, Harpe,
        HellsEgress, HellsIngress, SpinningScythe, InfernalSlice,
        WhorlofDeath, ArcaneCrest, NightmareScythe, BloodStalk,
        GrimSwathe, SoulSlice, SoulScythe, UnveiledGibbet,
        Guillotine, Gibbet, Gallows, UnveiledGallows,
        ArcaneCircle, Regress, Gluttony, GrimReaping,
        CrossReaping, VoidReaping, Enshroud, Soulsow,
        HarvestMoon, LemuresSlice, LemuresScythe, PlentifulHarvest,
        Communio, Sacrificium, ExecutionersGibbet, ExecutionersGallows,
        ExecutionersGuillotine, Perfectio, SecondWind, LegSweep,
        Bloodbath, Feint, ArmsLength, TrueNorth,
    ];

    public static readonly IReadOnlyList<StatusRef> AllStatuses =
    [
        FeintBuff, TrueNorthBuff,
    ];
}
