using OneTwoPunch.Core.Model;

namespace OneTwoPunch.Core.Jobs.Viper;

/// <summary>
/// Viper action and status ids.
/// <para>
/// Generated by <c>tools/generate_action_tables.py</c> from BossMod's ActionQueue
/// definitions (BSD 3-Clause), which are regenerated from the game's own data each
/// patch. Do not edit by hand - rerun the generator instead.
/// </para>
/// <para>
/// Ids are still verified against the game's Action and Status sheets at startup and
/// repaired by name on a mismatch, so a patch that shuffles them is corrected rather
/// than mis-cast.
/// </para>
/// </summary>
public static class ViperActions
{
    public static readonly ActionRef SteelFangs = new(34606, "Steel Fangs", ActionKind.Gcd, 1);
    public static readonly ActionRef HuntersSting = new(34608, "Hunters Sting", ActionKind.Gcd, 5);
    public static readonly ActionRef ReavingFangs = new(34607, "Reaving Fangs", ActionKind.Gcd, 10);
    public static readonly ActionRef WrithingSnap = new(34632, "Writhing Snap", ActionKind.Gcd, 15);
    public static readonly ActionRef SwiftskinsSting = new(34609, "Swiftskins Sting", ActionKind.Gcd, 20);
    public static readonly ActionRef SteelMaw = new(34614, "Steel Maw", ActionKind.Gcd, 25);
    public static readonly ActionRef FlankstingStrike = new(34610, "Flanksting Strike", ActionKind.Gcd, 30);
    public static readonly ActionRef FlanksbaneFang = new(34611, "Flanksbane Fang", ActionKind.Gcd, 30);
    public static readonly ActionRef HindstingStrike = new(34612, "Hindsting Strike", ActionKind.Gcd, 30);
    public static readonly ActionRef HindsbaneFang = new(34613, "Hindsbane Fang", ActionKind.Gcd, 30);
    public static readonly ActionRef ReavingMaw = new(34615, "Reaving Maw", ActionKind.Gcd, 35);
    public static readonly ActionRef Slither = new(34646, "Slither", ActionKind.OGcd, 40);
    public static readonly ActionRef HuntersBite = new(34616, "Hunters Bite", ActionKind.Gcd, 40);
    public static readonly ActionRef SwiftskinsBite = new(34617, "Swiftskins Bite", ActionKind.Gcd, 45);
    public static readonly ActionRef JaggedMaw = new(34618, "Jagged Maw", ActionKind.Gcd, 50);
    public static readonly ActionRef BloodiedMaw = new(34619, "Bloodied Maw", ActionKind.Gcd, 50);
    public static readonly ActionRef DeathRattle = new(34634, "Death Rattle", ActionKind.OGcd, 55);
    public static readonly ActionRef SerpentsTail = new(35920, "Serpents Tail", ActionKind.OGcd, 55);
    public static readonly ActionRef LastLash = new(34635, "Last Lash", ActionKind.OGcd, 60);
    public static readonly ActionRef Vicewinder = new(34620, "Vicewinder", ActionKind.Gcd, 65);
    public static readonly ActionRef HuntersCoil = new(34621, "Hunters Coil", ActionKind.Gcd, 65);
    public static readonly ActionRef SwiftskinsCoil = new(34622, "Swiftskins Coil", ActionKind.Gcd, 65);
    public static readonly ActionRef Vicepit = new(34623, "Vicepit", ActionKind.Gcd, 70);
    public static readonly ActionRef SwiftskinsDen = new(34625, "Swiftskins Den", ActionKind.Gcd, 70);
    public static readonly ActionRef HuntersDen = new(34624, "Hunters Den", ActionKind.Gcd, 70);
    public static readonly ActionRef TwinfangBite = new(34636, "Twinfang Bite", ActionKind.OGcd, 75);
    public static readonly ActionRef TwinbloodBite = new(34637, "Twinblood Bite", ActionKind.OGcd, 75);
    public static readonly ActionRef Twinblood = new(35922, "Twinblood", ActionKind.OGcd, 75);
    public static readonly ActionRef Twinfang = new(35921, "Twinfang", ActionKind.OGcd, 75);
    public static readonly ActionRef TwinfangThresh = new(34638, "Twinfang Thresh", ActionKind.OGcd, 80);
    public static readonly ActionRef TwinbloodThresh = new(34639, "Twinblood Thresh", ActionKind.OGcd, 80);
    public static readonly ActionRef UncoiledFury = new(34633, "Uncoiled Fury", ActionKind.Gcd, 82);
    public static readonly ActionRef SerpentsIre = new(34647, "Serpents Ire", ActionKind.OGcd, 86);
    public static readonly ActionRef ThirdGeneration = new(34629, "Third Generation", ActionKind.Gcd, 90);
    public static readonly ActionRef FourthGeneration = new(34630, "Fourth Generation", ActionKind.Gcd, 90);
    public static readonly ActionRef SecondGeneration = new(34628, "Second Generation", ActionKind.Gcd, 90);
    public static readonly ActionRef FirstGeneration = new(34627, "First Generation", ActionKind.Gcd, 90);
    public static readonly ActionRef Reawaken = new(34626, "Reawaken", ActionKind.Gcd, 90);
    public static readonly ActionRef UncoiledTwinfang = new(34644, "Uncoiled Twinfang", ActionKind.OGcd, 92);
    public static readonly ActionRef UncoiledTwinblood = new(34645, "Uncoiled Twinblood", ActionKind.OGcd, 92);
    public static readonly ActionRef Ouroboros = new(34631, "Ouroboros", ActionKind.Gcd, 96);
    public static readonly ActionRef FourthLegacy = new(34643, "Fourth Legacy", ActionKind.OGcd, 100);
    public static readonly ActionRef SecondLegacy = new(34641, "Second Legacy", ActionKind.OGcd, 100);
    public static readonly ActionRef FirstLegacy = new(34640, "First Legacy", ActionKind.OGcd, 100);
    public static readonly ActionRef ThirdLegacy = new(34642, "Third Legacy", ActionKind.OGcd, 100);
    public static readonly ActionRef SecondWind = new(7541, "Second Wind", ActionKind.OGcd, 8);
    public static readonly ActionRef LegSweep = new(7863, "Leg Sweep", ActionKind.OGcd, 10);
    public static readonly ActionRef Bloodbath = new(7542, "Bloodbath", ActionKind.OGcd, 12);
    public static readonly ActionRef Feint = new(7549, "Feint", ActionKind.OGcd, 22);
    public static readonly ActionRef ArmsLength = new(7548, "Arms Length", ActionKind.OGcd, 32);
    public static readonly ActionRef TrueNorth = new(7546, "True North", ActionKind.OGcd, 50);

    public static readonly StatusRef HuntersInstinct = new(3668, "Hunters Instinct");
    public static readonly StatusRef Swiftscaled = new(3669, "Swiftscaled");
    public static readonly StatusRef HonedSteel = new(3672, "Honed Steel");
    public static readonly StatusRef HonedReavers = new(3772, "Honed Reavers");
    public static readonly StatusRef HindstungVenom = new(3647, "Hindstung Venom");
    public static readonly StatusRef HindsbaneVenom = new(3648, "Hindsbane Venom");
    public static readonly StatusRef FlanksbaneVenom = new(3646, "Flanksbane Venom");
    public static readonly StatusRef FlankstungVenom = new(3645, "Flankstung Venom");
    public static readonly StatusRef GrimskinsVenom = new(3650, "Grimskins Venom");
    public static readonly StatusRef GrimhuntersVenom = new(3649, "Grimhunters Venom");
    public static readonly StatusRef HuntersVenom = new(3657, "Hunters Venom");
    public static readonly StatusRef SwiftskinsVenom = new(3658, "Swiftskins Venom");
    public static readonly StatusRef Reawakened = new(3670, "Reawakened");
    public static readonly StatusRef ReawakenReady = new(3671, "Reawaken Ready");
    public static readonly StatusRef FellhuntersVenom = new(3659, "Fellhunters Venom");
    public static readonly StatusRef FellskinsVenom = new(3660, "Fellskins Venom");
    public static readonly StatusRef TwinbloodfangST = new(3773, "Twinbloodfang ST");
    public static readonly StatusRef TwinbloodfangAOE = new(3774, "Twinbloodfang AOE");
    public static readonly StatusRef PoisedForTwinfang = new(3665, "Poised for Twinfang");
    public static readonly StatusRef PoisedForTwinblood = new(3666, "Poised for Twinblood");
    public static readonly StatusRef FeintBuff = new(1195, "Feint");
    public static readonly StatusRef TrueNorthBuff = new(1250, "True North");

    public static readonly IReadOnlyList<ActionRef> All =
    [
        SteelFangs, HuntersSting, ReavingFangs, WrithingSnap,
        SwiftskinsSting, SteelMaw, FlankstingStrike, FlanksbaneFang,
        HindstingStrike, HindsbaneFang, ReavingMaw, Slither,
        HuntersBite, SwiftskinsBite, JaggedMaw, BloodiedMaw,
        DeathRattle, SerpentsTail, LastLash, Vicewinder,
        HuntersCoil, SwiftskinsCoil, Vicepit, SwiftskinsDen,
        HuntersDen, TwinfangBite, TwinbloodBite, Twinblood,
        Twinfang, TwinfangThresh, TwinbloodThresh, UncoiledFury,
        SerpentsIre, ThirdGeneration, FourthGeneration, SecondGeneration,
        FirstGeneration, Reawaken, UncoiledTwinfang, UncoiledTwinblood,
        Ouroboros, FourthLegacy, SecondLegacy, FirstLegacy,
        ThirdLegacy, SecondWind, LegSweep, Bloodbath,
        Feint, ArmsLength, TrueNorth,
    ];

    public static readonly IReadOnlyList<StatusRef> AllStatuses =
    [
        HuntersInstinct, Swiftscaled, HonedSteel, HonedReavers,
        HindstungVenom, HindsbaneVenom, FlanksbaneVenom, FlankstungVenom,
        GrimskinsVenom, GrimhuntersVenom, HuntersVenom, SwiftskinsVenom,
        Reawakened, ReawakenReady, FellhuntersVenom, FellskinsVenom,
        TwinbloodfangST, TwinbloodfangAOE, PoisedForTwinfang, PoisedForTwinblood,
        FeintBuff, TrueNorthBuff,
    ];
}
