using TwoButton.Core.Model;

namespace TwoButton.Core.Jobs.Dancer;

/// <summary>
/// Dancer action and status ids.
/// <para>
/// Generated by <c>tools/generate_action_tables.py</c> from BossMod's ActionQueue
/// definitions (BSD 3-Clause), which are regenerated from the game's own data each
/// patch. Do not edit by hand - rerun the generator instead.
/// </para>
/// <para>
/// Ids are still verified against the game's Action and Status sheets at startup and
/// repaired by name on a mismatch, so a patch that shuffles them is corrected rather
/// than mis-cast.
/// </para>
/// </summary>
public static class DancerActions
{
    public static readonly ActionRef Cascade = new(15989, "Cascade", ActionKind.Gcd, 1);
    public static readonly ActionRef Fountain = new(15990, "Fountain", ActionKind.Gcd, 2);
    public static readonly ActionRef SingleStandardFinish = new(16191, "Single Standard Finish", ActionKind.Gcd, 15);
    public static readonly ActionRef DoubleStandardFinish = new(16192, "Double Standard Finish", ActionKind.Gcd, 15);
    public static readonly ActionRef StandardFinish = new(16003, "Standard Finish", ActionKind.Gcd, 15);
    public static readonly ActionRef Pirouette = new(16002, "Pirouette", ActionKind.Gcd, 15);
    public static readonly ActionRef Jete = new(16001, "Jete", ActionKind.Gcd, 15);
    public static readonly ActionRef Entrechat = new(16000, "Entrechat", ActionKind.Gcd, 15);
    public static readonly ActionRef Emboite = new(15999, "Emboite", ActionKind.Gcd, 15);
    public static readonly ActionRef Windmill = new(15993, "Windmill", ActionKind.Gcd, 15);
    public static readonly ActionRef StandardStep = new(15997, "Standard Step", ActionKind.Gcd, 15);
    public static readonly ActionRef ReverseCascade = new(15991, "Reverse Cascade", ActionKind.Gcd, 20);
    public static readonly ActionRef Bladeshower = new(15994, "Bladeshower", ActionKind.Gcd, 25);
    public static readonly ActionRef FanDance = new(16007, "Fan Dance", ActionKind.OGcd, 30);
    public static readonly ActionRef RisingWindmill = new(15995, "Rising Windmill", ActionKind.Gcd, 35);
    public static readonly ActionRef Fountainfall = new(15992, "Fountainfall", ActionKind.Gcd, 40);
    public static readonly ActionRef Bloodshower = new(15996, "Bloodshower", ActionKind.Gcd, 45);
    public static readonly ActionRef EnAvant = new(16010, "En Avant", ActionKind.OGcd, 50);
    public static readonly ActionRef FanDanceII = new(16008, "Fan Dance II", ActionKind.OGcd, 50);
    public static readonly ActionRef CuringWaltz = new(16015, "Curing Waltz", ActionKind.OGcd, 52);
    public static readonly ActionRef ShieldSamba = new(16012, "Shield Samba", ActionKind.OGcd, 56);
    public static readonly ActionRef ClosedPosition = new(16006, "Closed Position", ActionKind.OGcd, 60);
    public static readonly ActionRef Ending = new(18073, "Ending", ActionKind.OGcd, 60);
    public static readonly ActionRef Devilment = new(16011, "Devilment", ActionKind.OGcd, 62);
    public static readonly ActionRef FanDanceIII = new(16009, "Fan Dance III", ActionKind.OGcd, 66);
    public static readonly ActionRef TechnicalStep = new(15998, "Technical Step", ActionKind.Gcd, 70);
    public static readonly ActionRef TechnicalFinish = new(16004, "Technical Finish", ActionKind.Gcd, 70);
    public static readonly ActionRef SingleTechnicalFinish = new(16193, "Single Technical Finish", ActionKind.Gcd, 70);
    public static readonly ActionRef DoubleTechnicalFinish = new(16194, "Double Technical Finish", ActionKind.Gcd, 70);
    public static readonly ActionRef TripleTechnicalFinish = new(16195, "Triple Technical Finish", ActionKind.Gcd, 70);
    public static readonly ActionRef QuadrupleTechnicalFinish = new(16196, "Quadruple Technical Finish", ActionKind.Gcd, 70);
    public static readonly ActionRef SingleTechnicalFinish2 = new(33215, "Single Technical Finish II", ActionKind.Gcd, 70);
    public static readonly ActionRef DoubleTechnicalFinish2 = new(33216, "Double Technical Finish II", ActionKind.Gcd, 70);
    public static readonly ActionRef TripleTechnicalFinish2 = new(33217, "Triple Technical Finish II", ActionKind.Gcd, 70);
    public static readonly ActionRef QuadrupleTechnicalFinish2 = new(33218, "Quadruple Technical Finish II", ActionKind.Gcd, 70);
    public static readonly ActionRef Flourish = new(16013, "Flourish", ActionKind.OGcd, 72);
    public static readonly ActionRef SaberDance = new(16005, "Saber Dance", ActionKind.Gcd, 76);
    public static readonly ActionRef Improvisation = new(16014, "Improvisation", ActionKind.OGcd, 80);
    public static readonly ActionRef ImprovisedFinish = new(25789, "Improvised Finish", ActionKind.OGcd, 80);
    public static readonly ActionRef Tillana = new(25790, "Tillana", ActionKind.Gcd, 82);
    public static readonly ActionRef FanDanceIV = new(25791, "Fan Dance IV", ActionKind.OGcd, 86);
    public static readonly ActionRef StarfallDance = new(25792, "Starfall Dance", ActionKind.Gcd, 90);
    public static readonly ActionRef LastDance = new(36983, "Last Dance", ActionKind.Gcd, 1);
    public static readonly ActionRef FinishingMove = new(36984, "Finishing Move", ActionKind.Gcd, 1);
    public static readonly ActionRef DanceOfTheDawn = new(36985, "Dance of the Dawn", ActionKind.Gcd, 1);
    public static readonly ActionRef LegGraze = new(7554, "Leg Graze", ActionKind.OGcd, 6);
    public static readonly ActionRef SecondWind = new(7541, "Second Wind", ActionKind.OGcd, 8);
    public static readonly ActionRef FootGraze = new(7553, "Foot Graze", ActionKind.OGcd, 10);
    public static readonly ActionRef Peloton = new(7557, "Peloton", ActionKind.OGcd, 20);
    public static readonly ActionRef HeadGraze = new(7551, "Head Graze", ActionKind.OGcd, 24);
    public static readonly ActionRef ArmsLength = new(7548, "Arms Length", ActionKind.OGcd, 32);

    public static readonly StatusRef SilkenSymmetry = new(2693, "Silken Symmetry");
    public static readonly StatusRef Heavy = new(14, "Heavy");
    public static readonly StatusRef Bind = new(13, "Bind");
    public static readonly StatusRef ArmsLengthBuff = new(1209, "Arms Length");
    public static readonly StatusRef TechnicalStepBuff = new(1819, "Technical Step");
    public static readonly StatusRef FlourishingFinish = new(2698, "Flourishing Finish");
    public static readonly StatusRef TechnicalFinishBuff = new(1822, "Technical Finish");
    public static readonly StatusRef TechnicalEsprit = new(1848, "Technical Esprit");
    public static readonly StatusRef StandardFinishBuff = new(1821, "Standard Finish");
    public static readonly StatusRef StandardEsprit = new(1847, "Standard Esprit");
    public static readonly StatusRef StandardStepBuff = new(1818, "Standard Step");
    public static readonly StatusRef ImprovisationBuff = new(1827, "Improvisation");
    public static readonly StatusRef ImprovisedFinishBuff = new(2697, "Improvised Finish");
    public static readonly StatusRef ShieldSambaBuff = new(1826, "Shield Samba");
    public static readonly StatusRef DevilmentBuff = new(1825, "Devilment");
    public static readonly StatusRef FlourishingStarfall = new(2700, "Flourishing Starfall");
    public static readonly StatusRef FlourishingSymmetry = new(3017, "Flourishing Symmetry");
    public static readonly StatusRef FlourishingFlow = new(3018, "Flourishing Flow");
    public static readonly StatusRef ThreefoldFanDance = new(1820, "Threefold Fan Dance");
    public static readonly StatusRef FourfoldFanDance = new(2699, "Fourfold Fan Dance");
    public static readonly StatusRef SilkenFlow = new(2694, "Silken Flow");
    public static readonly StatusRef DancePartner = new(1824, "Dance Partner");
    public static readonly StatusRef ClosedPositionBuff = new(1823, "Closed Position");
    public static readonly StatusRef LastDanceReady = new(3867, "Last Dance Ready");
    public static readonly StatusRef FinishingMoveReady = new(3868, "Finishing Move Ready");
    public static readonly StatusRef DanceOfTheDawnReady = new(3869, "Dance of the Dawn Ready");
    public static readonly StatusRef PelotonBuff = new(1199, "Peloton");

    public static readonly IReadOnlyList<ActionRef> All =
    [
        Cascade, Fountain, SingleStandardFinish, DoubleStandardFinish,
        StandardFinish, Pirouette, Jete, Entrechat,
        Emboite, Windmill, StandardStep, ReverseCascade,
        Bladeshower, FanDance, RisingWindmill, Fountainfall,
        Bloodshower, EnAvant, FanDanceII, CuringWaltz,
        ShieldSamba, ClosedPosition, Ending, Devilment,
        FanDanceIII, TechnicalStep, TechnicalFinish, SingleTechnicalFinish,
        DoubleTechnicalFinish, TripleTechnicalFinish, QuadrupleTechnicalFinish, SingleTechnicalFinish2,
        DoubleTechnicalFinish2, TripleTechnicalFinish2, QuadrupleTechnicalFinish2, Flourish,
        SaberDance, Improvisation, ImprovisedFinish, Tillana,
        FanDanceIV, StarfallDance, LastDance, FinishingMove,
        DanceOfTheDawn, LegGraze, SecondWind, FootGraze,
        Peloton, HeadGraze, ArmsLength,
    ];

    public static readonly IReadOnlyList<StatusRef> AllStatuses =
    [
        SilkenSymmetry, Heavy, Bind, ArmsLengthBuff,
        TechnicalStepBuff, FlourishingFinish, TechnicalFinishBuff, TechnicalEsprit,
        StandardFinishBuff, StandardEsprit, StandardStepBuff, ImprovisationBuff,
        ImprovisedFinishBuff, ShieldSambaBuff, DevilmentBuff, FlourishingStarfall,
        FlourishingSymmetry, FlourishingFlow, ThreefoldFanDance, FourfoldFanDance,
        SilkenFlow, DancePartner, ClosedPositionBuff, LastDanceReady,
        FinishingMoveReady, DanceOfTheDawnReady, PelotonBuff,
    ];
}
