using OneTwoPunch.Core.Model;

namespace OneTwoPunch.Core.Jobs.Summoner;

/// <summary>
/// Summoner action and status ids.
/// <para>
/// Generated by <c>tools/generate_action_tables.py</c> from BossMod's ActionQueue
/// definitions (BSD 3-Clause), which are regenerated from the game's own data each
/// patch. Do not edit by hand - rerun the generator instead.
/// </para>
/// <para>
/// Ids are still verified against the game's Action and Status sheets at startup and
/// repaired by name on a mismatch, so a patch that shuffles them is corrected rather
/// than mis-cast.
/// </para>
/// </summary>
public static class SummonerActions
{
    public static readonly ActionRef Ruin1 = new(163, "Ruin", ActionKind.Gcd, 1);
    public static readonly ActionRef SummonCarbuncle = new(25798, "Summon Carbuncle", ActionKind.Gcd, 2);
    public static readonly ActionRef RadiantAegis = new(25799, "Radiant Aegis", ActionKind.OGcd, 2);
    public static readonly ActionRef Physick = new(16230, "Physick", ActionKind.Gcd, 4);
    public static readonly ActionRef Aethercharge = new(25800, "Aethercharge", ActionKind.Gcd, 6);
    public static readonly ActionRef SummonRuby = new(25802, "Summon Ruby", ActionKind.Gcd, 6);
    public static readonly ActionRef RubyRuin1 = new(25808, "Ruby Ruin", ActionKind.Gcd, 6);
    public static readonly ActionRef Gemshine = new(25883, "Gemshine", ActionKind.Gcd, 6);
    public static readonly ActionRef EnergyDrain = new(16508, "Energy Drain", ActionKind.OGcd, 10);
    public static readonly ActionRef Fester = new(181, "Fester", ActionKind.OGcd, 10);
    public static readonly ActionRef SummonTopaz = new(25803, "Summon Topaz", ActionKind.Gcd, 15);
    public static readonly ActionRef TopazRuin1 = new(25809, "Topaz Ruin", ActionKind.Gcd, 15);
    public static readonly ActionRef EmeraldRuin1 = new(25810, "Emerald Ruin", ActionKind.Gcd, 22);
    public static readonly ActionRef SummonEmerald = new(25804, "Summon Emerald", ActionKind.Gcd, 22);
    public static readonly ActionRef Outburst = new(16511, "Outburst", ActionKind.Gcd, 26);
    public static readonly ActionRef RubyOutburst = new(25814, "Ruby Outburst", ActionKind.Gcd, 26);
    public static readonly ActionRef EmeraldOutburst = new(25816, "Emerald Outburst", ActionKind.Gcd, 26);
    public static readonly ActionRef PreciousBrilliance = new(25884, "Precious Brilliance", ActionKind.Gcd, 26);
    public static readonly ActionRef TopazOutburst = new(25815, "Topaz Outburst", ActionKind.Gcd, 26);
    public static readonly ActionRef TopazRuin2 = new(25812, "Topaz Ruin II", ActionKind.Gcd, 30);
    public static readonly ActionRef EmeraldRuin2 = new(25813, "Emerald Ruin II", ActionKind.Gcd, 30);
    public static readonly ActionRef Ruin2 = new(172, "Ruin II", ActionKind.Gcd, 30);
    public static readonly ActionRef SummonIfrit1 = new(25805, "Summon Ifrit", ActionKind.Gcd, 30);
    public static readonly ActionRef RubyRuin2 = new(25811, "Ruby Ruin II", ActionKind.Gcd, 30);
    public static readonly ActionRef SummonTitan1 = new(25806, "Summon Titan", ActionKind.Gcd, 35);
    public static readonly ActionRef Painflare = new(3578, "Painflare", ActionKind.OGcd, 40);
    public static readonly ActionRef SummonGaruda1 = new(25807, "Summon Garuda", ActionKind.Gcd, 45);
    public static readonly ActionRef EnergySiphon = new(16510, "Energy Siphon", ActionKind.OGcd, 52);
    public static readonly ActionRef RubyRuin3 = new(25817, "Ruby Ruin III", ActionKind.Gcd, 54);
    public static readonly ActionRef Ruin3 = new(3579, "Ruin III", ActionKind.Gcd, 54);
    public static readonly ActionRef TopazRuin3 = new(25818, "Topaz Ruin III", ActionKind.Gcd, 54);
    public static readonly ActionRef EmeraldRuin3 = new(25819, "Emerald Ruin III", ActionKind.Gcd, 54);
    public static readonly ActionRef DreadwyrmTrance = new(3581, "Dreadwyrm Trance", ActionKind.Gcd, 58);
    public static readonly ActionRef AstralImpulse = new(25820, "Astral Impulse", ActionKind.Gcd, 58);
    public static readonly ActionRef AstralFlare = new(25821, "Astral Flare", ActionKind.Gcd, 58);
    public static readonly ActionRef Deathflare = new(3582, "Deathflare", ActionKind.OGcd, 60);
    public static readonly ActionRef AstralFlow = new(25822, "Astral Flow", ActionKind.Gcd, 60);
    public static readonly ActionRef Ruin4 = new(7426, "Ruin IV", ActionKind.Gcd, 62);
    public static readonly ActionRef SearingLight = new(25801, "Searing Light", ActionKind.OGcd, 66);
    public static readonly ActionRef SummonBahamut = new(7427, "Summon Bahamut", ActionKind.Gcd, 70);
    public static readonly ActionRef EnkindleBahamut = new(7429, "Enkindle Bahamut", ActionKind.OGcd, 70);
    public static readonly ActionRef TopazRite = new(25824, "Topaz Rite", ActionKind.Gcd, 72);
    public static readonly ActionRef EmeraldRite = new(25825, "Emerald Rite", ActionKind.Gcd, 72);
    public static readonly ActionRef RubyRite = new(25823, "Ruby Rite", ActionKind.Gcd, 72);
    public static readonly ActionRef TriDisaster = new(25826, "Tri Disaster", ActionKind.Gcd, 74);
    public static readonly ActionRef RubyDisaster = new(25827, "Ruby Disaster", ActionKind.Gcd, 74);
    public static readonly ActionRef TopazDisaster = new(25828, "Topaz Disaster", ActionKind.Gcd, 74);
    public static readonly ActionRef EmeraldDisaster = new(25829, "Emerald Disaster", ActionKind.Gcd, 74);
    public static readonly ActionRef Rekindle = new(25830, "Rekindle", ActionKind.OGcd, 80);
    public static readonly ActionRef SummonPhoenix = new(25831, "Summon Phoenix", ActionKind.Gcd, 80);
    public static readonly ActionRef EnkindlePhoenix = new(16516, "Enkindle Phoenix", ActionKind.OGcd, 80);
    public static readonly ActionRef BrandOfPurgatory = new(16515, "Br and of Purgatory", ActionKind.Gcd, 80);
    public static readonly ActionRef FountainOfFire = new(16514, "Founta in of Fire", ActionKind.Gcd, 80);
    public static readonly ActionRef RubyCatastrophe = new(25832, "Ruby Catastrophe", ActionKind.Gcd, 82);
    public static readonly ActionRef TopazCatastrophe = new(25833, "Topaz Catastrophe", ActionKind.Gcd, 82);
    public static readonly ActionRef EmeraldCatastrophe = new(25834, "Emerald Catastrophe", ActionKind.Gcd, 82);
    public static readonly ActionRef Slipstream = new(25837, "Slipstream", ActionKind.Gcd, 86);
    public static readonly ActionRef MountainBuster = new(25836, "Mounta in Buster", ActionKind.OGcd, 86);
    public static readonly ActionRef CrimsonCyclone = new(25835, "Crimson Cyclone", ActionKind.Gcd, 86);
    public static readonly ActionRef CrimsonStrike = new(25885, "Crimson Strike", ActionKind.Gcd, 86);
    public static readonly ActionRef SummonIfrit2 = new(25838, "Summon Ifrit II", ActionKind.Gcd, 90);
    public static readonly ActionRef SummonTitan2 = new(25839, "Summon Titan II", ActionKind.Gcd, 90);
    public static readonly ActionRef SummonGaruda2 = new(25840, "Summon Garuda II", ActionKind.Gcd, 90);
    public static readonly ActionRef Necrotize = new(36990, "Necrotize", ActionKind.OGcd, 92);
    public static readonly ActionRef SearingFlash = new(36991, "Searing Flash", ActionKind.OGcd, 96);
    public static readonly ActionRef UmbralImpulse = new(36994, "Umbral Impulse", ActionKind.Gcd, 100);
    public static readonly ActionRef UmbralFlare = new(36995, "Umbral Flare", ActionKind.Gcd, 100);
    public static readonly ActionRef Sunflare = new(36996, "Sunflare", ActionKind.OGcd, 100);
    public static readonly ActionRef LuxSolaris = new(36997, "Lux Solaris", ActionKind.OGcd, 100);
    public static readonly ActionRef EnkindleSolarBahamut = new(36998, "Enkindle Solar Bahamut", ActionKind.OGcd, 100);
    public static readonly ActionRef SummonSolarBahamut = new(36992, "Summon Solar Bahamut", ActionKind.Gcd, 100);
    public static readonly ActionRef Addle = new(7560, "Addle", ActionKind.OGcd, 8);
    public static readonly ActionRef Sleep = new(25880, "Sleep", ActionKind.Gcd, 10);
    public static readonly ActionRef Resurrection = new(173, "Resurrection", ActionKind.Gcd, 12);
    public static readonly ActionRef LucidDreaming = new(7562, "Lucid Dreaming", ActionKind.OGcd, 14);
    public static readonly ActionRef Swiftcast = new(7561, "Swiftcast", ActionKind.OGcd, 18);
    public static readonly ActionRef Surecast = new(7559, "Surecast", ActionKind.OGcd, 44);

    public static readonly StatusRef SleepBuff = new(3, "Sleep");
    public static readonly StatusRef FurtherRuin = new(2701, "Further Ruin");
    public static readonly StatusRef SearingLightBuff = new(2703, "Searing Light");
    public static readonly StatusRef TitansFavor = new(2853, "Titans Favor");
    public static readonly StatusRef RekindleBuff = new(2704, "Rekindle");
    public static readonly StatusRef RadiantAegisBuff = new(2702, "Radiant Aegis");
    public static readonly StatusRef SlipstreamBuff = new(2706, "Slipstream");
    public static readonly StatusRef IfritsFavor = new(2724, "Ifrits Favor");
    public static readonly StatusRef GarudasFavor = new(2725, "Garudas Favor");
    public static readonly StatusRef RubysGlimmer = new(3873, "Rubys Glimmer");
    public static readonly StatusRef RefulgentLux = new(3874, "Refulgent Lux");
    public static readonly StatusRef CrimsonStrikeReady = new(4403, "Crimson Strike Ready");
    public static readonly StatusRef DreadwyrmTranceBuff = new(3228, "Dreadwyrm Trance");
    public static readonly StatusRef FirebirdTrance = new(3229, "Firebird Trance");
    public static readonly StatusRef AddleBuff = new(1203, "Addle");
    public static readonly StatusRef SurecastBuff = new(160, "Surecast");
    public static readonly StatusRef LucidDreamingBuff = new(1204, "Lucid Dreaming");
    public static readonly StatusRef SwiftcastBuff = new(167, "Swiftcast");

    public static readonly IReadOnlyList<ActionRef> All =
    [
        Ruin1, SummonCarbuncle, RadiantAegis, Physick,
        Aethercharge, SummonRuby, RubyRuin1, Gemshine,
        EnergyDrain, Fester, SummonTopaz, TopazRuin1,
        EmeraldRuin1, SummonEmerald, Outburst, RubyOutburst,
        EmeraldOutburst, PreciousBrilliance, TopazOutburst, TopazRuin2,
        EmeraldRuin2, Ruin2, SummonIfrit1, RubyRuin2,
        SummonTitan1, Painflare, SummonGaruda1, EnergySiphon,
        RubyRuin3, Ruin3, TopazRuin3, EmeraldRuin3,
        DreadwyrmTrance, AstralImpulse, AstralFlare, Deathflare,
        AstralFlow, Ruin4, SearingLight, SummonBahamut,
        EnkindleBahamut, TopazRite, EmeraldRite, RubyRite,
        TriDisaster, RubyDisaster, TopazDisaster, EmeraldDisaster,
        Rekindle, SummonPhoenix, EnkindlePhoenix, BrandOfPurgatory,
        FountainOfFire, RubyCatastrophe, TopazCatastrophe, EmeraldCatastrophe,
        Slipstream, MountainBuster, CrimsonCyclone, CrimsonStrike,
        SummonIfrit2, SummonTitan2, SummonGaruda2, Necrotize,
        SearingFlash, UmbralImpulse, UmbralFlare, Sunflare,
        LuxSolaris, EnkindleSolarBahamut, SummonSolarBahamut, Addle,
        Sleep, Resurrection, LucidDreaming, Swiftcast,
        Surecast,
    ];

    public static readonly IReadOnlyList<StatusRef> AllStatuses =
    [
        SleepBuff, FurtherRuin, SearingLightBuff, TitansFavor,
        RekindleBuff, RadiantAegisBuff, SlipstreamBuff, IfritsFavor,
        GarudasFavor, RubysGlimmer, RefulgentLux, CrimsonStrikeReady,
        DreadwyrmTranceBuff, FirebirdTrance, AddleBuff, SurecastBuff,
        LucidDreamingBuff, SwiftcastBuff,
    ];
}
