using TwoButton.Core.Model;

namespace TwoButton.Core.Jobs.Samurai;

/// <summary>
/// Samurai action and status ids.
/// <para>
/// Generated by <c>tools/generate_action_tables.py</c> from BossMod's ActionQueue
/// definitions (BSD 3-Clause), which are regenerated from the game's own data each
/// patch. Do not edit by hand - rerun the generator instead.
/// </para>
/// <para>
/// Ids are still verified against the game's Action and Status sheets at startup and
/// repaired by name on a mismatch, so a patch that shuffles them is corrected rather
/// than mis-cast.
/// </para>
/// </summary>
public static class SamuraiActions
{
    public static readonly ActionRef Hakaze = new(7477, "Hakaze", ActionKind.Gcd, 1);
    public static readonly ActionRef Jinpu = new(7478, "Jinpu", ActionKind.Gcd, 4);
    public static readonly ActionRef ThirdEye = new(7498, "Third Eye", ActionKind.OGcd, 6);
    public static readonly ActionRef Enpi = new(7486, "Enpi", ActionKind.Gcd, 15);
    public static readonly ActionRef Shifu = new(7479, "Shifu", ActionKind.Gcd, 18);
    public static readonly ActionRef Fuga = new(7483, "Fuga", ActionKind.Gcd, 26);
    public static readonly ActionRef Iaijutsu = new(7867, "Iaijutsu", ActionKind.Gcd, 30);
    public static readonly ActionRef Gekko = new(7481, "Gekko", ActionKind.Gcd, 30);
    public static readonly ActionRef Higanbana = new(7489, "Higanbana", ActionKind.Gcd, 30);
    public static readonly ActionRef Mangetsu = new(7484, "Mangetsu", ActionKind.Gcd, 35);
    public static readonly ActionRef Kasha = new(7482, "Kasha", ActionKind.Gcd, 40);
    public static readonly ActionRef TenkaGoken = new(7488, "Tenka Goken", ActionKind.Gcd, 40);
    public static readonly ActionRef Oka = new(7485, "Oka", ActionKind.Gcd, 45);
    public static readonly ActionRef MidareSetsugekka = new(7487, "Midare Setsugekka", ActionKind.Gcd, 50);
    public static readonly ActionRef MeikyoShisui = new(7499, "Meikyo Shisui", ActionKind.OGcd, 50);
    public static readonly ActionRef Yukikaze = new(7480, "Yukikaze", ActionKind.Gcd, 50);
    public static readonly ActionRef HissatsuShinten = new(7490, "Hissatsu Shinten", ActionKind.OGcd, 52);
    public static readonly ActionRef HissatsuGyoten = new(7492, "Hissatsu Gyoten", ActionKind.OGcd, 54);
    public static readonly ActionRef HissatsuYaten = new(7493, "Hissatsu Yaten", ActionKind.OGcd, 56);
    public static readonly ActionRef Meditate = new(7497, "Meditate", ActionKind.Gcd, 60);
    public static readonly ActionRef HissatsuKyuten = new(7491, "Hissatsu Kyuten", ActionKind.OGcd, 62);
    public static readonly ActionRef Hagakure = new(7495, "Hagakure", ActionKind.OGcd, 68);
    public static readonly ActionRef Ikishoten = new(16482, "Ikishoten", ActionKind.OGcd, 68);
    public static readonly ActionRef HissatsuGuren = new(7496, "Hissatsu Guren", ActionKind.OGcd, 70);
    public static readonly ActionRef HissatsuSenei = new(16481, "Hissatsu Senei", ActionKind.OGcd, 72);
    public static readonly ActionRef TsubameGaeshi = new(16483, "Tsubame Gaeshi", ActionKind.Gcd, 76);
    public static readonly ActionRef KaeshiSetsugekka = new(16486, "Kaeshi Setsugekka", ActionKind.Gcd, 76);
    public static readonly ActionRef KaeshiGoken = new(16485, "Kaeshi Goken", ActionKind.Gcd, 76);
    public static readonly ActionRef Shoha = new(16487, "Shoha", ActionKind.OGcd, 80);
    public static readonly ActionRef Tengentsu = new(36962, "Tengentsu", ActionKind.OGcd, 82);
    public static readonly ActionRef Fuko = new(25780, "Fuko", ActionKind.Gcd, 86);
    public static readonly ActionRef OgiNamikiri = new(25781, "Ogi Namikiri", ActionKind.Gcd, 90);
    public static readonly ActionRef KaeshiNamikiri = new(25782, "Kaeshi Namikiri", ActionKind.Gcd, 90);
    public static readonly ActionRef Gyofu = new(36963, "Gyofu", ActionKind.Gcd, 92);
    public static readonly ActionRef Zanshin = new(36964, "Zanshin", ActionKind.OGcd, 96);
    public static readonly ActionRef TendoGoken = new(36965, "Tendo Goken", ActionKind.Gcd, 100);
    public static readonly ActionRef TendoSetsugekka = new(36966, "Tendo Setsugekka", ActionKind.Gcd, 100);
    public static readonly ActionRef TendoKaeshiGoken = new(36967, "Tendo Kaeshi Goken", ActionKind.Gcd, 100);
    public static readonly ActionRef TendoKaeshiSetsugekka = new(36968, "Tendo Kaeshi Setsugekka", ActionKind.Gcd, 100);
    public static readonly ActionRef SecondWind = new(7541, "Second Wind", ActionKind.OGcd, 8);
    public static readonly ActionRef LegSweep = new(7863, "Leg Sweep", ActionKind.OGcd, 10);
    public static readonly ActionRef Bloodbath = new(7542, "Bloodbath", ActionKind.OGcd, 12);
    public static readonly ActionRef Feint = new(7549, "Feint", ActionKind.OGcd, 22);
    public static readonly ActionRef ArmsLength = new(7548, "Arms Length", ActionKind.OGcd, 32);
    public static readonly ActionRef TrueNorth = new(7546, "True North", ActionKind.OGcd, 50);

    public static readonly StatusRef Fugetsu = new(1298, "Fugetsu");
    public static readonly StatusRef HiganbanaBuff = new(1228, "Higanbana");
    public static readonly StatusRef Fuka = new(1299, "Fuka");
    public static readonly StatusRef MeikyoShisuiBuff = new(1233, "Meikyo Shisui");
    public static readonly StatusRef KaeshiGokenBuff = new(3852, "Kaeshi Goken");
    public static readonly StatusRef KaeshiSetsugekkaBuff = new(4216, "Kaeshi Setsugekka");
    public static readonly StatusRef TendoKaeshiGokenBuff = new(4217, "Tendo Kaeshi Goken");
    public static readonly StatusRef TendoKaeshiSetsugekkaBuff = new(4218, "Tendo Kaeshi Setsugekka");
    public static readonly StatusRef EnhancedEnpi = new(1236, "Enhanced Enpi");
    public static readonly StatusRef MeditateBuff = new(1231, "Meditate");
    public static readonly StatusRef OgiNamikiriReady = new(2959, "Ogi Namikiri Ready");
    public static readonly StatusRef TengentsuBuff = new(3853, "Tengentsu");
    public static readonly StatusRef ZanshinReady = new(3855, "Zansh in Ready");
    public static readonly StatusRef Tendo = new(3856, "Tendo");
    public static readonly StatusRef TsubameReady = new(4216, "Tsubame Ready");
    public static readonly StatusRef FeintBuff = new(1195, "Feint");
    public static readonly StatusRef TrueNorthBuff = new(1250, "True North");

    public static readonly IReadOnlyList<ActionRef> All =
    [
        Hakaze, Jinpu, ThirdEye, Enpi,
        Shifu, Fuga, Iaijutsu, Gekko,
        Higanbana, Mangetsu, Kasha, TenkaGoken,
        Oka, MidareSetsugekka, MeikyoShisui, Yukikaze,
        HissatsuShinten, HissatsuGyoten, HissatsuYaten, Meditate,
        HissatsuKyuten, Hagakure, Ikishoten, HissatsuGuren,
        HissatsuSenei, TsubameGaeshi, KaeshiSetsugekka, KaeshiGoken,
        Shoha, Tengentsu, Fuko, OgiNamikiri,
        KaeshiNamikiri, Gyofu, Zanshin, TendoGoken,
        TendoSetsugekka, TendoKaeshiGoken, TendoKaeshiSetsugekka, SecondWind,
        LegSweep, Bloodbath, Feint, ArmsLength,
        TrueNorth,
    ];

    public static readonly IReadOnlyList<StatusRef> AllStatuses =
    [
        Fugetsu, HiganbanaBuff, Fuka, MeikyoShisuiBuff,
        KaeshiGokenBuff, KaeshiSetsugekkaBuff, TendoKaeshiGokenBuff, TendoKaeshiSetsugekkaBuff,
        EnhancedEnpi, MeditateBuff, OgiNamikiriReady, TengentsuBuff,
        ZanshinReady, Tendo, TsubameReady, FeintBuff,
        TrueNorthBuff,
    ];
}
