using OneTwoPunch.Core.Model;

namespace OneTwoPunch.Core.Jobs.DarkKnight;

/// <summary>
/// DarkKnight action and status ids.
/// <para>
/// Generated by <c>tools/generate_action_tables.py</c> from BossMod's ActionQueue
/// definitions (BSD 3-Clause), which are regenerated from the game's own data each
/// patch. Do not edit by hand - rerun the generator instead.
/// </para>
/// <para>
/// Ids are still verified against the game's Action and Status sheets at startup and
/// repaired by name on a mismatch, so a patch that shuffles them is corrected rather
/// than mis-cast.
/// </para>
/// </summary>
public static class DarkKnightActions
{
    public static readonly ActionRef HardSlash = new(3617, "Hard Slash", ActionKind.Gcd, 1);
    public static readonly ActionRef SyphonStrike = new(3623, "Syphon Strike", ActionKind.Gcd, 2);
    public static readonly ActionRef Unleash = new(3621, "Unleash", ActionKind.Gcd, 6);
    public static readonly ActionRef Grit = new(3629, "Grit", ActionKind.OGcd, 10);
    public static readonly ActionRef ReleaseGrit = new(32067, "Release Grit", ActionKind.OGcd, 10);
    public static readonly ActionRef Unmend = new(3624, "Unmend", ActionKind.Gcd, 15);
    public static readonly ActionRef Souleater = new(3632, "Souleater", ActionKind.Gcd, 26);
    public static readonly ActionRef FloodOfDarkness = new(16466, "Flood of Darkness", ActionKind.OGcd, 30);
    public static readonly ActionRef BloodWeapon = new(3625, "Blood Weapon", ActionKind.OGcd, 35);
    public static readonly ActionRef ShadowWall = new(3636, "Shadow Wall", ActionKind.OGcd, 38);
    public static readonly ActionRef EdgeOfDarkness = new(16467, "Edge of Darkness", ActionKind.OGcd, 40);
    public static readonly ActionRef StalwartSoul = new(16468, "Stalwart Soul", ActionKind.Gcd, 40);
    public static readonly ActionRef DarkMind = new(3634, "Dark Mind", ActionKind.OGcd, 45);
    public static readonly ActionRef LivingDead = new(3638, "Living Dead", ActionKind.OGcd, 50);
    public static readonly ActionRef SaltedEarth = new(3639, "Salted Earth", ActionKind.OGcd, 52);
    public static readonly ActionRef Shadowstride = new(36926, "Shadowstride", ActionKind.OGcd, 54);
    public static readonly ActionRef AbyssalDrain = new(3641, "Abyssal Drain", ActionKind.OGcd, 56);
    public static readonly ActionRef CarveAndSpit = new(3643, "Carve and Spit", ActionKind.OGcd, 60);
    public static readonly ActionRef Bloodspiller = new(7392, "Bloodspiller", ActionKind.Gcd, 62);
    public static readonly ActionRef Quietus = new(7391, "Quietus", ActionKind.Gcd, 64);
    public static readonly ActionRef Delirium = new(7390, "Delirium", ActionKind.OGcd, 68);
    public static readonly ActionRef TheBlackestNight = new(7393, "The Blackest Night", ActionKind.OGcd, 70);
    public static readonly ActionRef EdgeOfShadow = new(16470, "Edge of Shadow", ActionKind.OGcd, 74);
    public static readonly ActionRef FloodOfShadow = new(16469, "Flood of Shadow", ActionKind.OGcd, 74);
    public static readonly ActionRef DarkMissionary = new(16471, "Dark Missionary", ActionKind.OGcd, 76);
    public static readonly ActionRef LivingShadow = new(16472, "Living Shadow", ActionKind.OGcd, 80);
    public static readonly ActionRef Oblation = new(25754, "Oblation", ActionKind.OGcd, 82);
    public static readonly ActionRef SaltAndDarkness = new(25755, "Salt and Darkness", ActionKind.OGcd, 86);
    public static readonly ActionRef SaltAndDarknessEnd = new(25756, "Salt and Darkness End", ActionKind.Gcd, 86);
    public static readonly ActionRef Shadowbringer = new(25757, "Shadowbringer", ActionKind.OGcd, 90);
    public static readonly ActionRef ShadowedVigil = new(36927, "Shadowed Vigil", ActionKind.OGcd, 92);
    public static readonly ActionRef ScarletDelirium = new(36928, "Scarlet Delirium", ActionKind.Gcd, 96);
    public static readonly ActionRef Comeuppance = new(36929, "Comeuppance", ActionKind.Gcd, 96);
    public static readonly ActionRef Torcleaver = new(36930, "Torcleaver", ActionKind.Gcd, 96);
    public static readonly ActionRef Impalement = new(36931, "Impalement", ActionKind.Gcd, 96);
    public static readonly ActionRef Disesteem = new(36932, "Disesteem", ActionKind.Gcd, 100);
    public static readonly ActionRef Rampart = new(7531, "Rampart", ActionKind.OGcd, 8);
    public static readonly ActionRef LowBlow = new(7540, "Low Blow", ActionKind.OGcd, 12);
    public static readonly ActionRef Provoke = new(7533, "Provoke", ActionKind.OGcd, 15);
    public static readonly ActionRef Interject = new(7538, "Interject", ActionKind.OGcd, 18);
    public static readonly ActionRef Reprisal = new(7535, "Reprisal", ActionKind.OGcd, 22);
    public static readonly ActionRef ArmsLength = new(7548, "Arms Length", ActionKind.OGcd, 32);
    public static readonly ActionRef Shirk = new(7537, "Shirk", ActionKind.OGcd, 48);

    public static readonly StatusRef BloodWeaponBuff = new(742, "Blood Weapon");
    public static readonly StatusRef GritBuff = new(743, "Grit");
    public static readonly StatusRef SaltedEarthBuff = new(749, "Salted Earth");
    public static readonly StatusRef TheBlackestNightBuff = new(1178, "The Blackest Night");
    public static readonly StatusRef DeliriumBuff = new(1972, "Delirium");
    public static readonly StatusRef OblationBuff = new(2682, "Oblation");
    public static readonly StatusRef EnhancedDelirium = new(3836, "Enhanced Delirium");
    public static readonly StatusRef Scorn = new(3837, "Scorn");
    public static readonly StatusRef ReprisalBuff = new(1193, "Reprisal");

    public static readonly IReadOnlyList<ActionRef> All =
    [
        HardSlash, SyphonStrike, Unleash, Grit,
        ReleaseGrit, Unmend, Souleater, FloodOfDarkness,
        BloodWeapon, ShadowWall, EdgeOfDarkness, StalwartSoul,
        DarkMind, LivingDead, SaltedEarth, Shadowstride,
        AbyssalDrain, CarveAndSpit, Bloodspiller, Quietus,
        Delirium, TheBlackestNight, EdgeOfShadow, FloodOfShadow,
        DarkMissionary, LivingShadow, Oblation, SaltAndDarkness,
        SaltAndDarknessEnd, Shadowbringer, ShadowedVigil, ScarletDelirium,
        Comeuppance, Torcleaver, Impalement, Disesteem,
        Rampart, LowBlow, Provoke, Interject,
        Reprisal, ArmsLength, Shirk,
    ];

    public static readonly IReadOnlyList<StatusRef> AllStatuses =
    [
        BloodWeaponBuff, GritBuff, SaltedEarthBuff, TheBlackestNightBuff,
        DeliriumBuff, OblationBuff, EnhancedDelirium, Scorn,
        ReprisalBuff,
    ];
}
