using OneTwoPunch.Core.Model;

namespace OneTwoPunch.Core.Jobs.Paladin;

/// <summary>
/// Paladin action and status ids.
/// <para>
/// Generated by <c>tools/generate_action_tables.py</c> from BossMod's ActionQueue
/// definitions (BSD 3-Clause), which are regenerated from the game's own data each
/// patch. Do not edit by hand - rerun the generator instead.
/// </para>
/// <para>
/// Ids are still verified against the game's Action and Status sheets at startup and
/// repaired by name on a mismatch, so a patch that shuffles them is corrected rather
/// than mis-cast.
/// </para>
/// </summary>
public static class PaladinActions
{
    public static readonly ActionRef FastBlade = new(9, "Fast Blade", ActionKind.Gcd, 1);
    public static readonly ActionRef FightOrFlight = new(20, "Fight or Flight", ActionKind.OGcd, 2);
    public static readonly ActionRef RiotBlade = new(15, "Riot Blade", ActionKind.Gcd, 4);
    public static readonly ActionRef TotalEclipse = new(7381, "Total Eclipse", ActionKind.Gcd, 6);
    public static readonly ActionRef ReleaseIronWill = new(32065, "Release Iron Will", ActionKind.OGcd, 10);
    public static readonly ActionRef IronWill = new(28, "Iron Will", ActionKind.OGcd, 10);
    public static readonly ActionRef ShieldBash = new(16, "Shield Bash", ActionKind.Gcd, 10);
    public static readonly ActionRef ShieldLob = new(24, "Shield Lob", ActionKind.Gcd, 15);
    public static readonly ActionRef RageOfHalone = new(21, "Rage of Halone", ActionKind.Gcd, 26);
    public static readonly ActionRef SpiritsWithin = new(29, "Spirits Within", ActionKind.OGcd, 30);
    public static readonly ActionRef Sheltron = new(3542, "Sheltron", ActionKind.OGcd, 35);
    public static readonly ActionRef Sentinel = new(17, "Sentinel", ActionKind.OGcd, 38);
    public static readonly ActionRef Prominence = new(16457, "Prominence", ActionKind.Gcd, 40);
    public static readonly ActionRef Cover = new(27, "Cover", ActionKind.OGcd, 45);
    public static readonly ActionRef CircleOfScorn = new(23, "Circle of Scorn", ActionKind.OGcd, 50);
    public static readonly ActionRef HallowedGround = new(30, "Hallowed Ground", ActionKind.OGcd, 50);
    public static readonly ActionRef Bulwark = new(22, "Bulwark", ActionKind.OGcd, 52);
    public static readonly ActionRef GoringBlade = new(3538, "Goring Blade", ActionKind.Gcd, 54);
    public static readonly ActionRef DivineVeil = new(3540, "Divine Veil", ActionKind.OGcd, 56);
    public static readonly ActionRef Clemency = new(3541, "Clemency", ActionKind.Gcd, 58);
    public static readonly ActionRef RoyalAuthority = new(3539, "Royal Authority", ActionKind.Gcd, 60);
    public static readonly ActionRef Intervention = new(7382, "Intervention", ActionKind.OGcd, 62);
    public static readonly ActionRef HolySpirit = new(7384, "Holy Spirit", ActionKind.Gcd, 64);
    public static readonly ActionRef Requiescat = new(7383, "Requiescat", ActionKind.OGcd, 68);
    public static readonly ActionRef PassageOfArms = new(7385, "Passage of Arms", ActionKind.OGcd, 70);
    public static readonly ActionRef HolyCircle = new(16458, "Holy Circle", ActionKind.Gcd, 72);
    public static readonly ActionRef Intervene = new(16461, "Intervene", ActionKind.OGcd, 74);
    public static readonly ActionRef Atonement = new(16460, "Atonement", ActionKind.Gcd, 76);
    public static readonly ActionRef Supplication = new(36918, "Supplication", ActionKind.Gcd, 76);
    public static readonly ActionRef Sepulchre = new(36919, "Sepulchre", ActionKind.Gcd, 76);
    public static readonly ActionRef Confiteor = new(16459, "Confiteor", ActionKind.Gcd, 80);
    public static readonly ActionRef HolySheltron = new(25746, "Holy Sheltron", ActionKind.OGcd, 82);
    public static readonly ActionRef Expiacion = new(25747, "Expiacion", ActionKind.OGcd, 86);
    public static readonly ActionRef BladeOfFaith = new(25748, "Blade of Faith", ActionKind.Gcd, 90);
    public static readonly ActionRef BladeOfTruth = new(25749, "Blade of Truth", ActionKind.Gcd, 90);
    public static readonly ActionRef BladeOfValor = new(25750, "Blade of Valor", ActionKind.Gcd, 90);
    public static readonly ActionRef Guardian = new(36920, "Guardian", ActionKind.OGcd, 92);
    public static readonly ActionRef Imperator = new(36921, "Imperator", ActionKind.OGcd, 96);
    public static readonly ActionRef BladeOfHonor = new(36922, "Blade of Honor", ActionKind.OGcd, 100);
    public static readonly ActionRef Rampart = new(7531, "Rampart", ActionKind.OGcd, 8);
    public static readonly ActionRef LowBlow = new(7540, "Low Blow", ActionKind.OGcd, 12);
    public static readonly ActionRef Provoke = new(7533, "Provoke", ActionKind.OGcd, 15);
    public static readonly ActionRef Interject = new(7538, "Interject", ActionKind.OGcd, 18);
    public static readonly ActionRef Reprisal = new(7535, "Reprisal", ActionKind.OGcd, 22);
    public static readonly ActionRef ArmsLength = new(7548, "Arms Length", ActionKind.OGcd, 32);
    public static readonly ActionRef Shirk = new(7537, "Shirk", ActionKind.OGcd, 48);

    public static readonly StatusRef FightOrFlightBuff = new(76, "Fight or Flight");
    public static readonly StatusRef IronWillBuff = new(79, "Iron Will");
    public static readonly StatusRef GoringBladeReady = new(3847, "Goring Blade Ready");
    public static readonly StatusRef RequiescatBuff = new(1368, "Requiescat");
    public static readonly StatusRef ConfiteorReady = new(3019, "Confiteor Ready");
    public static readonly StatusRef CircleOfScornBuff = new(248, "Circle of Scorn");
    public static readonly StatusRef AtonementReady = new(1902, "Atonement Ready");
    public static readonly StatusRef DivineMight = new(2673, "Divine Might");
    public static readonly StatusRef SupplicationReady = new(3827, "Supplication Ready");
    public static readonly StatusRef SepulchreReady = new(3828, "Sepulchre Ready");
    public static readonly StatusRef BladeOfHonorReady = new(3831, "Blade of Honor Ready");
    public static readonly StatusRef ReprisalBuff = new(1193, "Reprisal");

    public static readonly IReadOnlyList<ActionRef> All =
    [
        FastBlade, FightOrFlight, RiotBlade, TotalEclipse,
        ReleaseIronWill, IronWill, ShieldBash, ShieldLob,
        RageOfHalone, SpiritsWithin, Sheltron, Sentinel,
        Prominence, Cover, CircleOfScorn, HallowedGround,
        Bulwark, GoringBlade, DivineVeil, Clemency,
        RoyalAuthority, Intervention, HolySpirit, Requiescat,
        PassageOfArms, HolyCircle, Intervene, Atonement,
        Supplication, Sepulchre, Confiteor, HolySheltron,
        Expiacion, BladeOfFaith, BladeOfTruth, BladeOfValor,
        Guardian, Imperator, BladeOfHonor, Rampart,
        LowBlow, Provoke, Interject, Reprisal,
        ArmsLength, Shirk,
    ];

    public static readonly IReadOnlyList<StatusRef> AllStatuses =
    [
        FightOrFlightBuff, IronWillBuff, GoringBladeReady, RequiescatBuff,
        ConfiteorReady, CircleOfScornBuff, AtonementReady, DivineMight,
        SupplicationReady, SepulchreReady, BladeOfHonorReady, ReprisalBuff,
    ];
}
