using TwoButton.Core.Model;

namespace TwoButton.Core.Jobs.RedMage;

/// <summary>
/// RedMage action and status ids.
/// <para>
/// Generated by <c>tools/generate_action_tables.py</c> from BossMod's ActionQueue
/// definitions (BSD 3-Clause), which are regenerated from the game's own data each
/// patch. Do not edit by hand - rerun the generator instead.
/// </para>
/// <para>
/// Ids are still verified against the game's Action and Status sheets at startup and
/// repaired by name on a mismatch, so a patch that shuffles them is corrected rather
/// than mis-cast.
/// </para>
/// </summary>
public static class RedMageActions
{
    public static readonly ActionRef Riposte = new(7504, "Riposte", ActionKind.Gcd, 1);
    public static readonly ActionRef EnchantedRiposte = new(7527, "Enchanted Riposte", ActionKind.Gcd, 1);
    public static readonly ActionRef Jolt = new(7503, "Jolt", ActionKind.Gcd, 2);
    public static readonly ActionRef Verthunder = new(7505, "Verthunder", ActionKind.Gcd, 4);
    public static readonly ActionRef CorpsACorps = new(7506, "Corps A Corps", ActionKind.OGcd, 6);
    public static readonly ActionRef Veraero = new(7507, "Veraero", ActionKind.Gcd, 10);
    public static readonly ActionRef Scatter = new(7509, "Scatter", ActionKind.Gcd, 15);
    public static readonly ActionRef VerthunderII = new(16524, "Verthunder II", ActionKind.Gcd, 18);
    public static readonly ActionRef VeraeroII = new(16525, "Veraero II", ActionKind.Gcd, 22);
    public static readonly ActionRef Verfire = new(7510, "Verfire", ActionKind.Gcd, 26);
    public static readonly ActionRef Verstone = new(7511, "Verstone", ActionKind.Gcd, 30);
    public static readonly ActionRef Zwerchhau = new(7512, "Zwerchhau", ActionKind.Gcd, 35);
    public static readonly ActionRef EnchantedZwerchhau = new(7528, "Enchanted Zwerchhau", ActionKind.Gcd, 35);
    public static readonly ActionRef Engagement = new(16527, "Engagement", ActionKind.OGcd, 40);
    public static readonly ActionRef Displacement = new(7515, "Displacement", ActionKind.OGcd, 40);
    public static readonly ActionRef Fleche = new(7517, "Fleche", ActionKind.OGcd, 45);
    public static readonly ActionRef EnchantedRedoublement = new(7529, "Enchanted Redoublement", ActionKind.Gcd, 50);
    public static readonly ActionRef Acceleration = new(7518, "Acceleration", ActionKind.OGcd, 50);
    public static readonly ActionRef Redoublement = new(7516, "Redoublement", ActionKind.Gcd, 50);
    public static readonly ActionRef EnchantedMoulinetTrois = new(37003, "Enchanted Moulinet Trois", ActionKind.Gcd, 52);
    public static readonly ActionRef EnchantedMoulinetDeux = new(37002, "Enchanted Moulinet Deux", ActionKind.Gcd, 52);
    public static readonly ActionRef Moulinet = new(7513, "Moulinet", ActionKind.Gcd, 52);
    public static readonly ActionRef EnchantedMoulinet = new(7530, "Enchanted Moulinet", ActionKind.Gcd, 52);
    public static readonly ActionRef Vercure = new(7514, "Vercure", ActionKind.Gcd, 54);
    public static readonly ActionRef ContreSixte = new(7519, "Contre Sixte", ActionKind.OGcd, 56);
    public static readonly ActionRef Embolden = new(7520, "Embolden", ActionKind.OGcd, 58);
    public static readonly ActionRef Manafication = new(7521, "Manafication", ActionKind.OGcd, 60);
    public static readonly ActionRef JoltII = new(7524, "Jolt II", ActionKind.Gcd, 62);
    public static readonly ActionRef Verraise = new(7523, "Verraise", ActionKind.Gcd, 64);
    public static readonly ActionRef Impact = new(16526, "Impact", ActionKind.Gcd, 66);
    public static readonly ActionRef Verflare = new(7525, "Verflare", ActionKind.Gcd, 68);
    public static readonly ActionRef Verholy = new(7526, "Verholy", ActionKind.Gcd, 70);
    public static readonly ActionRef Reprise = new(16529, "Reprise", ActionKind.Gcd, 76);
    public static readonly ActionRef EnchantedReprise = new(16528, "Enchanted Reprise", ActionKind.Gcd, 76);
    public static readonly ActionRef Scorch = new(16530, "Scorch", ActionKind.Gcd, 80);
    public static readonly ActionRef VerthunderIII = new(25855, "Verthunder III", ActionKind.Gcd, 82);
    public static readonly ActionRef VeraeroIII = new(25856, "Veraero III", ActionKind.Gcd, 82);
    public static readonly ActionRef JoltIII = new(37004, "Jolt III", ActionKind.Gcd, 84);
    public static readonly ActionRef MagickBarrier = new(25857, "Magick Barrier", ActionKind.OGcd, 86);
    public static readonly ActionRef Resolution = new(25858, "Resolution", ActionKind.Gcd, 90);
    public static readonly ActionRef ViceOfThorns = new(37005, "Vice Of Thorns", ActionKind.OGcd, 92);
    public static readonly ActionRef GrandImpact = new(37006, "Gr and Impact", ActionKind.Gcd, 96);
    public static readonly ActionRef Prefulgence = new(37007, "Prefulgence", ActionKind.OGcd, 100);
    public static readonly ActionRef Addle = new(7560, "Addle", ActionKind.OGcd, 8);
    public static readonly ActionRef Sleep = new(25880, "Sleep", ActionKind.Gcd, 10);
    public static readonly ActionRef LucidDreaming = new(7562, "Lucid Dreaming", ActionKind.OGcd, 14);
    public static readonly ActionRef Swiftcast = new(7561, "Swiftcast", ActionKind.OGcd, 18);
    public static readonly ActionRef Surecast = new(7559, "Surecast", ActionKind.OGcd, 44);

    public static readonly StatusRef VerfireReady = new(1234, "Verfire Ready");
    public static readonly StatusRef VerstoneReady = new(1235, "Verstone Ready");
    public static readonly StatusRef AccelerationBuff = new(1238, "Acceleration");
    public static readonly StatusRef EmboldenSelf = new(1239, "Embolden Self");
    public static readonly StatusRef Dualcast = new(1249, "Dualcast");
    public static readonly StatusRef EmboldenBuff = new(1297, "Embolden");
    public static readonly StatusRef ManaficationBuff = new(1971, "Manafication");
    public static readonly StatusRef MagickedSwordplay = new(3875, "Magicked Swordplay");
    public static readonly StatusRef ThornedFlourish = new(3876, "Thorned Flourish");
    public static readonly StatusRef GrandImpactReady = new(3877, "Gr and Impact Ready");
    public static readonly StatusRef PrefulgenceReady = new(3878, "Prefulgence Ready");
    public static readonly StatusRef AddleBuff = new(1203, "Addle");
    public static readonly StatusRef SurecastBuff = new(160, "Surecast");
    public static readonly StatusRef LucidDreamingBuff = new(1204, "Lucid Dreaming");
    public static readonly StatusRef SwiftcastBuff = new(167, "Swiftcast");

    public static readonly IReadOnlyList<ActionRef> All =
    [
        Riposte, EnchantedRiposte, Jolt, Verthunder,
        CorpsACorps, Veraero, Scatter, VerthunderII,
        VeraeroII, Verfire, Verstone, Zwerchhau,
        EnchantedZwerchhau, Engagement, Displacement, Fleche,
        EnchantedRedoublement, Acceleration, Redoublement, EnchantedMoulinetTrois,
        EnchantedMoulinetDeux, Moulinet, EnchantedMoulinet, Vercure,
        ContreSixte, Embolden, Manafication, JoltII,
        Verraise, Impact, Verflare, Verholy,
        Reprise, EnchantedReprise, Scorch, VerthunderIII,
        VeraeroIII, JoltIII, MagickBarrier, Resolution,
        ViceOfThorns, GrandImpact, Prefulgence, Addle,
        Sleep, LucidDreaming, Swiftcast, Surecast,
    ];

    public static readonly IReadOnlyList<StatusRef> AllStatuses =
    [
        VerfireReady, VerstoneReady, AccelerationBuff, EmboldenSelf,
        Dualcast, EmboldenBuff, ManaficationBuff, MagickedSwordplay,
        ThornedFlourish, GrandImpactReady, PrefulgenceReady, AddleBuff,
        SurecastBuff, LucidDreamingBuff, SwiftcastBuff,
    ];
}
